### ISSUE TITLE
typescript - functions

### ISSUE THREAD

**Issue by alancampora** [mhartington/nvim-typescript#102]
# Problems summary
When using functions like the following: 
```javascript
function superName(a: number, b: number) {
    return a + b;
}

// superName( , no suggestions but after removing the ( superName shows the popup
```
When I write superName, I don't see any suggestions till I press the "(" and then remove it.

## Expected
I would expect to see the suggestion while writhing superName

## Environment Information

 * terminal: iterm2 Build 3.1.5
 * vim/nvim version:NVIM v0.2.0 Build type: Release

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" deoplete config
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1

"typescript plugs
Plug 'Shougo/deoplete.nvim'
Plug 'mhartington/nvim-typescript'
Plug 'Quramy/tsuquyomi'
Plug 'Shougo/vimproc.vim', {'do' : 'make'}
Plug 'leafgarland/typescript-vim'

```

Is this the expected behaviour? I hope you can help me!
Thanks :D

**Comment by mhartington** [comment]
Hm, Im not able to recreate this locally.
![nvim-102](https://user-images.githubusercontent.com/2835826/33769484-647ba878-dbf8-11e7-9407-e1facacc896b.gif)

My only thought is that there could be some issues with having both this plugin and tsuquyomi running at the same time?

**Comment by alancampora** [comment]
Hi @mhartington thanks for your response!
Regarding tsuquyomi, I've just removed it but still the same issue. What's weird is that when I press superName and (, I see many other results.

<img width="592" alt="ts nvim" src="https://user-images.githubusercontent.com/4420832/33771025-5352e078-dc0e-11e7-8338-f26c19953e92.png">

But I'm not sure from where I'm getting all those results

**Comment by alancampora** [comment]
oh ok, then they are ok. 
So what I'm expecting is what you're showing in your sample. I create a function somewhere in the file, and if I start writing its name I get the suggestion. 
My issue is that for doing that I have to write the whole function name and the (, remove it and that's when I get the suggestion with the types.

What plugin are you using for recording your terminal ?

**Comment by alancampora** [comment]
Hi @mhartington, I've just finally made it work reinstalling deoplete and using just 
let g:deoplete#enable_at_startup = 1. 

Thanks!
