### ISSUE TITLE
Plugin does not work on Windows

### ISSUE THREAD

**Issue by Luladjiev** [mhartington/nvim-typescript#104]
# Problems summary
On Windows this plugin does not work. The problem is that on this [line](https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim_typescript/client.py#L51) the check_output needs to have shell=True

## Expected
To work

## Environment Information

 * terminal: Using neovim-qt
 * vim/nvim version: Neovim 0.2.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'mhartington/nvim-typescript'
call plug#end()

set runtimepath+=~/.local/share/nvim/plugged/nvim-typescript
```

## The reproduce ways from neovim starting

 1. Open a .ts file

## Example project repo?

No need of a project

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/4628170/34322347-35469694-e82d-11e7-8c7c-f5c7de3ba803.png)

**Comment by mhartington** [comment]
Ahh, good catch. Will fix in a bit

**Comment by mhartington** [comment]
Should be fixed now!
