### ISSUE TITLE
Not working with nvim-completion-manager

### ISSUE THREAD

**Issue by suzuki11109** [mhartington/nvim-typescript#105]
It's not working with nvim-completion-manager in both typescript and javascript files.

<img width="637" alt="screen shot 2017-12-29 at 16 09 25" src="https://user-images.githubusercontent.com/4640086/34433559-d505070e-ecb2-11e7-99f7-c5e881ede69c.png">

Thanks

**Comment by DonnieWest** [comment]
Looks like the error is here whenever javascript support is enabled https://github.com/mhartington/nvim-typescript/blob/master/autoload/cm/sources/typescript.vim#L6

I think I have some time to throw together a fix in the next day or two
