### ISSUE TITLE
Error in neovim on windows

### ISSUE THREAD

**Issue by samuelnilsson** [mhartington/nvim-typescript#113]
# Problems summary
The error message shown in the screenshot below appears when opening a typescript file in neovim in windows.

## Expected
That no error should appear.

## Environment Information

 * terminal: neovim-qt
 * vim/nvim version: NVIM v.0.2.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'mhartington/nvim-typescript'
Plug 'Shougo/deoplete.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting

 1. Open a typescript file

## Example project repo?

Should not be needed

## Screen shot (if possible)
![error](https://image.ibb.co/c7YkWw/Capture.png)

**Comment by mhartington** [comment]
Should be fixed now! Thanks
