### ISSUE TITLE
g:deoplete#auto_complete_start_length is not respected

### ISSUE THREAD

**Issue by epeli** [mhartington/nvim-typescript#117]
# Problems summary

I have set `g:deoplete#auto_complete_start_length = 3` but when I type just one character the popup menu appears. 

## Expected

The menu should appear only after the third char.

This isssue goes a way with typescript files if the nvim-typescript plugin is disabled. So I don't think it's an issue with deoplete. 

## Environment Information

 * nvim: v0.2.2
 * nvim-typescript b5e78fd583d27e890ecec21aef5bd5702c114e8b (current master)
* deoplete: from the `4.0-serial` tag  as suggested here https://github.com/mhartington/nvim-typescript/issues/115#issuecomment-364027502
* leafgarland/typescript-vim version 04e0d82
## init.vim

```vim
call plug#begin()
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'mhartington/nvim-typescript', { 'do': ':UpdateRemotePlugins' }
  Plug 'leafgarland/typescript-vim'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_start_length = 3
```

## Screen shots

nvim-typescript enabled:

![image](https://user-images.githubusercontent.com/225712/35980979-ca6a289e-0cf4-11e8-8f2d-1ed78477b651.png)

without nvim-typescript:

![image](https://user-images.githubusercontent.com/225712/35981125-2ddb5a56-0cf5-11e8-8129-f9c2b064db00.png)

**Comment by mhartington** [comment]
This make sense. I have 

```
        self.min_pattern_length = 1
```

Set in the source (my own personal preference). That variable is actually deprecated

https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L154-L158


Instead, use 

```
call deoplete#custom#source( typescript', 'min_pattern_length', 3)
```

**Comment by epeli** [comment]
Hmm, I'm not seeing any difference with that. I tried even editing the property in `nvim-typescript/rplugin/python3/deoplete/sources/typescript.py` directly and no change.

**Comment by epeli** [comment]
Also it seems that it autocompletes even with space:

![image](https://user-images.githubusercontent.com/225712/35981929-318674c2-0cf7-11e8-88f5-d7ecb27b500f.png)

I have listchars enabled in this screenshot so the space is visible.

**Comment by mhartington** [comment]
Hmm, alright I'll take a look

**Comment by Shougo** [comment]
https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py#L34

It is wrong.

```
				*deoplete-source-attribute-input_pattern*
input_pattern
		(String)			(Optional)
		If it is matched, deoplete ignores
		|deoplete-source-attribute-min_pattern_length|.
		It is useful for omni function sources.
		Note: If the source set the attribute, it must define
		|deoplete-source-attribute-get_complete_position| attribute.
		Note: It is Python3 regexp.

		If you omit it, this feature is ignored.
```

**Comment by Shougo** [comment]
`.` pattern matches any texts.
So your min_pattern_length is ignored.

**Comment by epeli** [comment]
I can confirm that this issue goes away if `self.input_pattern = r'.'` is set to something that does not match anything.

Interestingly thou

    call deoplete#custom#source( typescript', 'min_pattern_length', 3)

does not have any affect but the legacy

    let g:deoplete#auto_complete_start_length = 3

works.

**Comment by mhartington** [comment]
Will fix. Thanks for the info.

**Comment by mhartington** [comment]
This should be fixed in the singleton branch. Could you test it out and verify for me?

**Comment by mhartington** [comment]
Should be fixed and in master!
