### ISSUE TITLE
E117 Unknown function TSOnBufEnter when opening a .ts file

### ISSUE THREAD

**Issue by foxbunny** [mhartington/nvim-typescript#119]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

Using the code at current `master`  (6c67a84), I get the following error when opening a .ts file on NeoVim under Windows.

## Expected

Not to get an error. :)

## Environment Information

 * terminal: Command Prompt (Win 10, starting NeoVim using nvim-qt)
 * vim/nvim version: v0.2.3-712-g422a788b8

## Provide a minimal vim rc with less than 50 lines (Required!)

I don't have a minimal, but I have an exact config that you can clone [over here](https://github.com/foxbunny/vimfiles/tree/ts-improve) if that works for you.

## The reproduce ways from neovim starting

 1. Start NeoVim
 2. Open a .ts file

## Example project repo?

Will try to put something together if the above info doesn't help.

## Screen shot (if possible)

![image](https://user-images.githubusercontent.com/65413/36563669-31142f50-181b-11e8-9b69-533f2ccde4e6.png)

**Comment by mhartington** [comment]
Please run `UpdateRemotePlugins`

**Comment by foxbunny** [comment]
How embarrassing. I was sure I ran that. That got me past that, but now I have this traceback:

![image](https://user-images.githubusercontent.com/65413/36564010-27ce7d78-181c-11e8-8a5d-f4ecb495ed14.png)

Not sure what it's looking for, but I imagine it's either `tsc` or `tsserver`. I'm using `nvm-windows` which sets up a symlink at `C:\Program Files\NodeJS` pointing at `C:\NodeJS`. Is it possible that it's failing to follow the symlink?

**Comment by mhartington** [comment]
Hmm, it could be that. I'm away from my windows laptop, so I cannot test at the moment. I will test in a bit.

**Comment by foxbunny** [comment]
Thanks for looking into it. 👍

**Comment by kreedz** [comment]
Same issue on windows and nvim.
I'm getting this when in the first time open *.tsx file:
![2602-nvm-ts](https://user-images.githubusercontent.com/2128965/36668324-c4257066-1b12-11e8-8d1e-9423fca61d01.png)
It's exactly the same output as foxbunny's except last line.

tsc is installed globally and in console actually I can run tsc.

**Comment by cmcclellen** [comment]
@foxbunny @kreedz 
I was able to get it working by modifying client.py in the rplugin subdirectory of the plugin.   On Windows, there are 3 major things to do:

1) Make sure the CWD of neovim is your project root, that holds your node_modules.  

2)  in client.py, in the function `start(should_debug, debug_options)`, I had to change the code a little:
```python
def start(should_debug, debug_options):
    """
    start proc
    """
    global server_handle
    global serverPath
    global __environ

    # https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts
    if server_handle is None:
        if should_debug is not 0:
            __environ['TSS_LOG'] = "-logToFile true -file {0} -level {1}".format(
                debug_options['file'], debug_options['level'])
        command = serverPath.replace('/','\\')
        server_handle = subprocess.Popen(
            [command,"--disableAutomaticTypingAcquisition"],
            env=__environ,
            cwd=os.getcwd(),
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=None,
            universal_newlines=True,
            bufsize=-1,
	    shell=True
        )
        return True
    else:
        return
```

The major thing is turning forward slashes into back slashes, and then shell=True at the end of the subprocess.Popen, as tsserver is just a cmd file.

3) Similar situation in setTsConfigVersion():
```python
def setTsConfigVersion():
    global tsConfigVersion
    global serverPath
    command = serverPath.replace('tsserver', 'tsc')
    command = command.replace('/', '\\')
    rawOutput = subprocess.check_output([command, '--version'], shell=True)
    # strip nightly
    pure_version = rawOutput.rstrip().decode(
        'utf-8').split(' ').pop().split('-')[0]
    [major, minor, patch] = pure_version.split('.')[:3]
    tsConfigVersion = {"major": int(
        major), "minor": int(minor), "patch": int(patch)}
```

Again, changing the forward slashes to back slashes, and shell=True

This got it working for me on Windows 10.  Not saying this is a permanent fix, but hopefully can help the author.  Perhaps constructing paths via os.path.join() for defaults, like:
```os.path.join('node_modules','.bin','tsserver')```

**Comment by foxbunny** [comment]
> The major thing is turning forward slashes into back slashes, and then shell=True at the end of the subprocess.Popen, as tsserver is just a cmd file.

This is probably a task well-suited to the [`normpath()`](https://docs.python.org/2/library/os.path.html#os.path.normpath) function.

> and then shell=True

Looks good.

I'll try these modifications tomorrow and report back.

**Comment by foxbunny** [comment]
As you can see, PR is submitted. I haven't yet tested the full functionality, but this gets rid of all the errors and I see that TS Server is started. The docs are missing the instructions for configuring omnicomplete, and it does not work out of the box. As I'm not using any of the suggested completion plugins, that is left for another time. :)

**Comment by mhartington** [comment]
This should be fixed! If you all could verify that would be great!

**Comment by foxbunny** [comment]
Confirming that the fix works
