### ISSUE TITLE
Long term goals

### ISSUE THREAD

**Issue by mhartington** [mhartington/nvim-typescript#12]
Just some random plans/ideas I have for this project.
- [x] Extract the TSServer client out into it's own class. This will give a good base for what I want to do.
- [x] Use neovims remote pluing API and build out more features. GOTO/Rename Symbol/Definitions. 
  All of this is provided by the language service API/TSS. It can be as simple as 

```
  def _GetDoc( self, request_data ):
    self._Reload( request_data )
    info = self._SendRequest( 'quickinfo', {
      'file':   request_data[ 'filepath' ],
      'line':   request_data[ 'line_num' ],
      'offset': request_data[ 'column_codepoint' ]
    } )
```

_[Taken from ycmd](https://github.com/Valloric/ycmd/blob/master/ycmd/completers/typescript/typescript_completer.py#L451)_
- [x] Make faster! Currently, if there is a large list returned from the subprocess, trying to return the completion detail is not great. It can really slow down the whole thing. Not sure how this can be done, but it's a long term goal 😁

**Comment by mhartington** [comment]
Note, this is open to all who have contributed before and any new contributors. If you have some ideas, I would love to hear them!

**Comment by faceleg** [comment]
- [ ] Add function argument completion, similar to VSCode

**Comment by prabirshrestha** [comment]
I wonder how it would to implement the common language server protocol (https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol) with deoplete so it works easily with other langauges too.

The protocol currently has these features
- common way to report errors/warnings
- execute commands
- autocomplete requests
- hover information
- request signature
- goto definition
- find references

I had opened the issue here https://github.com/Shougo/deoplete.nvim/issues/324

**Comment by mhartington** [comment]
Grand Idea/scheme  is this.


Single server instance gets created on opening supported filetypes.

That server would handle most of the functionality. 
Making it handle completion/docs/gotDef/etc would be rather easy then.

Most of it is just sending the correct message.


For definitions, it would look something like this
```
self._SendRequest( 'definition', {
  'file':   request_data[ 'filepath' ],
  'line':   request_data[ 'line_num' ],
  'offset': request_data[ 'column_codepoint' ]
})
```

For refactoring/renaming, something like this.
```
self._SendRequest( 'rename', {
  'file':   request_data[ 'filepath' ],
  'line':   request_data[ 'line_num' ],
  'offset': request_data[ 'column_codepoint' ],
      'findInComments': False,
      'findInStrings': False,
})
```

I have it all fleshed out in my head, but dont have a lot of time to extract the server. That's the key to making everything work really. 


If you happen to get a PR together, I would gladly accept it!

**Comment by mhartington** [comment]
I have added `TSDef`,  `TSDoc`, and `TSType`to the plugin. 🎉
