### ISSUE TITLE
Reference filepath not updated

### ISSUE THREAD

**Issue by sQVe** [mhartington/nvim-typescript#122]
# Problems summary
Reference filepath does not update when changing `PWD`.

## Expected
The files should take current `PWD` in account and correctly list the filepath.

## Environment Information

 * terminal: rxvt-unicode
 * vim/nvim version: neovim 0.2.2-3

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Just to get Plug. Not relevant to the issue
if empty(glob('~/.config/nvim/autoload/plug.vim'))
silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

call plug#begin()

function! DoRemote(arg)
  UpdateRemotePlugins
endfunction

" Install nvim typescript so we can use it's commands
Plug 'mhartington/nvim-typescript'

call plug#end()

```

## The reproduce ways from neovim starting

  1. Start nvim in `$HOME`.
  2. Change `PWD` to another folder, in this example `$HOMe/code/liftsaga`.
  3. Run the `TSRef` command on a symbol and get a list of references.
  4. All paths will pointing from `$HOME` and not the current `PWD`.

## Example project repo?

I'm using https://github.com/sQVe/liftsaga here but this problems occurs will all projects.

## Screen shot (if possible)
![nvim-typscript-reference-bug](https://user-images.githubusercontent.com/2284724/37431211-e84b26b0-27d4-11e8-87e3-26990c2ae4f7.gif)

**Comment by mhartington** [comment]
Hmm, alright. I think this is something that I never though people would do I guess 😄 

Can you test out this little snippet and let me know if it will update? 

```vim
au DirChanged * call TSOnBufSave()
```

**Comment by sQVe** [comment]
@mhartington Yeah, I assumed that this was a classic case of _"different workflow"_. I rarely change my `pwd` but it happens occasionally, and when it does it breaks reference lookup and I have to restart nvim (which is a bit of a hassle).

I tried setting `au DirChanged * call TSOnBufSave()` in my config but that did not solve the problem.

There is also some other small inconsistencies with how the reference window work. If I open a reference which points to the current open buffer it stays open but if it points to a different buffer / file it clears the reference list. See flow below:

![nvim-typescript-references-cleared](https://user-images.githubusercontent.com/2284724/37447960-a7de189e-2824-11e8-883f-b31867b9cae8.gif)

**Comment by mhartington** [comment]
Going to close this for now. Im not sure this is something we can support in the plugin. But I'll happily accept a PR to fix this.
