### ISSUE TITLE
Allow :TSDef to load definition in window that already has buffer open

### ISSUE THREAD

**Issue by dlee** [mhartington/nvim-typescript#123]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
`:TSDef` always opens the file in the current window even if the file is loaded in another window.

## Expected
I would like to optionally have `:TSDef` take me to the definition in another window if another window already has the buffer opened.

## Environment Information

 * terminal: iTerm2
 * vim/nvim version: NVIM v0.2.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
autocmd FileType typescript nmap <buffer> <c-]> :TSDef<CR>
```

## The reproduce ways from neovim starting
1. Place cursor over variable declared in another buffer
2. Do `:TSDef`
3. It will load the buffer in the current window instead of taking you to the definition in the window that already has the buffer open.

**Comment by mhartington** [comment]
I've added this to the upcoming node rewrite branch.

![buffer-or-window](https://user-images.githubusercontent.com/2835826/40309547-e8592336-5cd7-11e8-8509-8388842ba685.gif)

If you'd like to test it out, please see https://github.com/mhartington/nvim-typescript/issues/128#issuecomment-390531683 for the details. I would love to get a few more testers to verify everything is working for folks
