### ISSUE TITLE
Allow passing of options to `tsserver`

### ISSUE THREAD

**Issue by stellarhoof** [mhartington/nvim-typescript#127]
# Problems summary

I'd like to pass options to `tsserver`. The server assumes `npm` is installed in the same location as `node` by default, but this is not necessarily so, which is why they provide an option `--npmLocation` to configure it. If `tsserver` cannot find the `npm` binary, it won't be able to download typings for the project automatically.

**Comment by mhartington** [comment]
Sounds like a reasonable request! I'll get it added

**Comment by mhartington** [comment]
Should be in now.

```
let g:nvim_typescript#server_options = ['--noGetErrOnBackgroundUpdate', 'true']
```

Or any valid server option
