### ISSUE TITLE
RFC: Move to node/js from python

### ISSUE THREAD

**Issue by mhartington** [mhartington/nvim-typescript#128]
Im in progress of moving from the python API to Neovim's node API. 
There's some pros and cons to this so I figured I'd leave a comment for anyone who uses this plugin to address their concerns/questions.

Pros
- easier to maintain. Python has become a pain to work with for me (as it's not my day-to-day lang). Moving to JS would make maintenance  much easier and possibly allow for more contributors.
- Typescript. Using a typescript plugin to author the typescript plugin. Generally, easier to know what data types are being sent and coming back from the tsserver process.
- Speed and buffer size. Python has some speed and buffer size limits when dealing with tsserver, and right now there's a lot of hacks in place to make sure this plugin doesn't break the subprocess. Node child_process does not have this issue.

I will post more updates as I get further along, but I'm overall really pleased with the ease of migration. 

I'll also create a python specific tag of the plugin for those who want to stay on it, but typically, if you're using Typescript, you have node installed, so this should be a welcomed change.

**Comment by pyrho** [comment]
Awesome ! Don't hesitate to ask if you need more manpower on this.

**Comment by pyrho** [comment]
```
>>> a = [1, 2, 3]
>>> a
[1, 2, 3]
>>> a[:2]
[1, 2]
```

Basically [the code you mentioned](https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim_typescript/__init__.py#L370-L371) code says: "Take the substring of `lineToChange` from the begining up to `changeOffset - 1` :)

See: https://docs.python.org/3/tutorial/introduction.html#lists

**Comment by mhartington** [comment]
Progress update: Most of the core functionality has been migrated! 

Deoplete is actually able to handle calling the vim function and returning it's value really well! 

Code maintenance is really good as well. The code is much easier to understand, especially for those coming from node/JS.

![nvim-node-almost](https://user-images.githubusercontent.com/2835826/39733121-16b7771c-523f-11e8-94de-5050a559cf23.gif)

**Comment by mhartington** [comment]
*Update* 

The plugin is ready for testing! 

This requires the neovim package installed globally

```shell
npm install -g neovim
```

And your nvim version needs to be 0.2.1 or newer.

```viml

" dein example
call dein#add('mhartington/nvim_typescript', {'rev': 'next-node', 'build': './install.sh'})

" vim plug
Plug 'mhartington/nvim_typescript', { 'branch': 'next-node', 'do': './install.sh' }
```

Please test it out and let me know if you run into any issues. Let's hope to get this into master this week and tag the python version for backwards-compat.

**Comment by pyrho** [comment]
Thanks ! Will test it throughout the day.
I guess `:UpdateRemotePlugins` should be run too (since the plugin changed from a python to a node host).

**Comment by pyrho** [comment]
Not a single issue for me so far. Good job !

**Comment by DonnieWest** [comment]
Works fantastically over here. This is awesome :)

**Comment by bmalinconico** [comment]
Working much better for me.

**Comment by mhartington** [comment]
Here is fine. If you're up for it, feel free to send a PR against the next-node branch. Would love to see if others are finding the new code base much easier to understand.

**Comment by mhartington** [comment]
This should be fixed.
![import-fix](https://user-images.githubusercontent.com/2835826/40694685-a62fb168-638b-11e8-8141-4b9b2439f441.gif)

I think with this, I will merge the changes into master and make the python codebase it's own branch. Thanks to those who tested and provided feedback. It was greatly appreciated.

**Comment by mhartington** [comment]
Node refactor is in master!
