### ISSUE TITLE
No completions of properties on first dot

### ISSUE THREAD

**Issue by kornosaurus** [mhartington/nvim-typescript#131]
# Problems summary
No typescript completions after `.` only after next char typed. Trying to get a list of all possible properties of an object but it will only complete after putting down another character, i.e. `obj.f`

## Expected
Getting a list of all members when completing an object, `obj.` should show a list of all properties of `obj`

## Environment Information

 * terminal: alacritty / gnome terminal
 * vim/nvim version: NVIM v0.2.2
 * typescript version: 2.4.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Just to get Plug. Not relevant to the issue
if empty(glob('~/.config/nvim/autoload/plug.vim'))
silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin()
function! DoRemote(arg)
  UpdateRemotePlugins
endfunction
" Actual configuration
Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') } " Autocompletion
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript'
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting
 1. on a newline type `obj.`
 2. now type `obj.f` and `foo` will appear

## Example project repo?
```typescript
const obj = { foo: 123, bar: '123' };

/* obj.
 * nothing
 */

/* obj.f
 * foo shows up
 */
```

## Screen shot (if possible)
![ts](https://user-images.githubusercontent.com/10253840/40043997-6cdc4e0a-5826-11e8-8800-4398a995d51f.gif)

**Comment by mhartington** [comment]
Should be fixed! Thanks for the issue

![131](https://user-images.githubusercontent.com/2835826/40285741-9f51e76e-5c6d-11e8-863e-f52f3a6f4f27.gif)
