### ISSUE TITLE
E117: Unknown function: TSOnBufEnter

### ISSUE THREAD

**Issue by bogem** [mhartington/nvim-typescript#137]
# Problems summary
This error appears when opening any .ts file with the plugin active, and the plugin doesn't work (no autocompletion for .ts files):

```
Error detected while processing BufEnter Auto commands for "*.ts":
E117: Unknown function: TSOnBufEnter
```

Yes, I know it's not the first issue about it. I read all tickets about this issue and tried to do everything that there is written. I did `:UpdateRemotePlugins` many times and it didn't help me:
```
remote/host: node host registered plugins ['nvim_typescript']
remote/host: python3 host registered plugins ['deoplete', 'far']
remote/host: generated rplugin manifest: /Users/albert/.local/share/nvim/rplugin.vim
```

## Expected

No errors

## Environment Information

 * terminal:
iterm 3.1.6 + tmux 2.7

 * vim/nvim version:
```
$ nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled  brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

            default vimrc: "$VIM/sysinit.vim"
          default $VIM : "
/usr/local/Cellar/neovim/0.2.2_1/share/nvim"

Run :checkhealth for more info
```

`:CheckHealth`:
```
health#nvim_typescript#check
========================================================================
## Find Node
  - OK: node is in $PATH

## Find Local Typescript
  - WARNING: No local server found, using global
    - ADVICE:
      - Install typescript locally for more accurate tooling
          $ npm install typescript --save-dev

## Find Global Typescript
  - OK: global tsserver is found

## Check for node bindings
  - OK: node bindings found

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: screen
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.2.6
  - OK: Latest python2-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.5
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v10.1.0
  - INFO: Host: /usr/local/bin/neovim-node-host
  - OK: Latest "neovim" npm is installed: 4.0.1
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set nocompatible

call plug#begin('~/.vim/plugged')
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neco-syntax'
Plug 'SirVer/ultisnips'
Plug 'Valloric/YouCompleteMe'
Plug 'zchee/deoplete-go', { 'do': 'make' }
call plug#end()
filetype plugin on

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting

Open .ts or .tsx file

**Comment by mertnuhoglu** [comment]
I have the same issue.

## Environment Information

    $ nvim --version
    NVIM v0.2.2
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/config -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20171118-36724-uevp4/neovim-0.2.2/build/include
    Compiled by brew@ElCapitan-2.local

    Features: +acl +iconv +jemalloc +tui 
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2/share/nvim"

    Run :checkhealth for more info

nvim `:CheckHealth`

    health#nvim_typescript#check
    ========================================================================
    ## Find Node
      - OK: node is in $PATH

    ## Find Local Typescript
      - WARNING: No local server found, using global
        - ADVICE:
          - Install typescript locally for more accurate tooling
              $ npm install typescript --save-dev

    ## Find Global Typescript
      - OK: global tsserver is found

    ## Check for node bindings
      - OK: node bindings found

    health#deoplete#check
    ========================================================================
    ## deoplete.nvim
      - OK: has("nvim") was successful
      - OK: exists("v:t_list") was successful
      - OK: has("timers") was successful
      - OK: has("python3") was successful
      - INFO: If you're still having problems, try the following commands:
        $ export NVIM_PYTHON_LOG_FILE=/tmp/log
        $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
        $ nvim
        $ cat /tmp/log_{PID}
        and then create an issue on github

    health#nvim#check
    ========================================================================
    ## Configuration
      - OK: no issues found

    ## Performance
      - OK: Build type: Release

    ## Remote Plugins
      - OK: Up to date

    ## terminal
      - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
      - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
      - INFO: $XTERM_VERSION=''
      - INFO: $VTE_VERSION=''
      - INFO: $COLORTERM=''
      - INFO: $SSH_TTY=''

    ## tmux
      - OK: escape-time: 0ms
      - INFO: $TERM: screen-256color

    health#provider#check
    ========================================================================
    ## Clipboard (optional)
      - OK: Clipboard tool found: pbcopy

    ## Python 2 provider (optional)
      - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
      - WARNING: provider/pythonx: Could not load Python 2:
        python2 not found in search path or not executable.
        /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
        /usr/bin/python2.6 does not have the "neovim" module. :help |provider-python|
        /usr/local/bin/python is Python 3.6 and cannot provide Python 2.
      - ERROR: Python provider error
        - ADVICE:
          - provider/pythonx: Could not load Python 2:
              python2 not found in search path or not executable.
              /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
              /usr/bin/python2.6 does not have the "neovim" module. :help |provider-python|
              /usr/local/bin/python is Python 3.6 and cannot provide Python 2.
      - INFO: Executable: Not found

    ## Python 3 provider (optional)
      - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
      - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
      - INFO: Executable: /usr/local/bin/python3
      - INFO: Other python executable: /Users/mertnuhoglu/miniconda3/bin/python3
      - INFO: Python3 version: 3.6.4
      - INFO: python3-neovim version: 0.2.4 (outdated; from /usr/local/lib/python3.6/site-packages/neovim)
      - WARNING: Latest python3-neovim is NOT installed: 0.2.6

    ## Ruby provider (optional)
      - INFO: Ruby: ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-darwin15]
      - INFO: Host: /Users/mertnuhoglu/.rvm/gems/ruby-2.1.1/bin/neovim-ruby-host
      - ERROR: Command timed out: 'gem' 'list' '-ra' '^neovim$'
      - ERROR: Failed to run: gem list -ra ^neovim$
        - ADVICE:
          - Make sure you're connected to the internet.
          - Are you behind a firewall or proxy?

    ## Node provider (optional)
      - INFO: Node: v10.0.0
      - WARNING: Missing "neovim" npm package.
        - ADVICE:
          - Run in shell: npm install -g neovim
          - Is the npm bin directory in $PATH?

## Provide a minimal vim rc with less than 50 lines (Required!)

    set runtimepath^=~/.vim runtimepath+=~/.vim/after
    let &packpath = &runtimepath
    call plug#begin('~/.vim/bundle')
    Plug 'mhartington/nvim-typescript'
    " autocomplete
    Plug 'Shougo/deoplete.nvim'
    call plug#end()

    let g:deoplete#enable_at_startup = 1
    syntax on

## The reproduce ways from neovim starting

Open .ts or .tsx file

**Comment by pyrho** [comment]
The typescript needs to be transpiled to javascript for this plugin to work now.

Since you're using VimPlug, you need to add this line:
`Plug 'mhartington/nvim-typescript', { 'do': './install.sh > /tmp/nvimtsinstall.log 2>&1' }`
(I redirected the error and standard output to the `/tmp/nvimtsinstall.log` file to be able to debug potential issues).

Unless you do that, there are no Javascript files for node plugin host to use.

**Comment by bogem** [comment]
@pyrho Run. Still the same 😣

**Comment by bogem** [comment]
I reinstalled nvim-typescript and executed `./install.sh`. It fixed the issue. Thank you, @pyrho!

**Comment by adc17** [comment]
This hasn't worked for me, I'm still seeing the error message.

**Comment by mhartington** [comment]
@adc17 could you open a new issues with all the detail you can provide?

**Comment by kyrisu** [comment]
@adc17 - update this line in your init.vim:
https://github.com/adc17/dotfiles/blob/7791cc9866bc97e9433cd1834f7ccea0bddf3465/nvim/init.vim#L59

You have:
```
Plug 'mhartington/nvim-typescript', { 'for': ['typescript', 'tsx'], 'do': ':UpdateRemotePlugins' }
```

It should be:
```
Plug 'mhartington/nvim-typescript', {'for': ['typescript', 'tsx'], 'do': './install.sh' }
```

I don't know why but had the same thing in my init.vim for some reason.

**Comment by adc17** [comment]
Nope, I guess I'll open my own issue.
