### ISSUE TITLE
nvim-typescript doesn't work with echodoc

### ISSUE THREAD

**Issue by bogem** [mhartington/nvim-typescript#140]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
After entering something and selecting candidate from autocompletion, there is no echodoc appearing. Echodoc works perfectly with other languages though. 

## Environment Information

 * terminal: iterm 3.1.6 + tmux 2.7

 * vim/nvim version: nvim 0.3.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
Plug 'leafgarland/typescript-vim'
Plug 'mhartington/nvim-typescript', { 'do': './install.sh' }
Plug 'Shougo/echodoc.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neco-syntax'
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'Valloric/YouCompleteMe'

"------- echodoc settings -------
let g:echodoc#enable_at_startup = 1
set cmdheight=2
"------- End echodoc settings ---

"------- deoplete settings -------
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('auto_complete_delay', 30)

" Silence the  messages in the command line
" such as 'The only match', 'Pattern not found', 'Back at original", etc.
set shortmess+=c

" Show neosnippet first
call deoplete#custom#source('neosnippet', 'rank', 1010)

" Don't show doc window
set completeopt-=preview

let g:nvim_typescript#max_completion_detail = 100
"------- End deoplete settings ---
```

## Screen shot (if possible)
1. Entering:
![screen shot 2018-06-18 at 14 02 11](https://user-images.githubusercontent.com/13235519/41534825-3f2db0a8-7300-11e8-8232-f8b857876427.png)

2. After selecting (after ctrl-y pressed):
![screen shot 2018-06-18 at 14 02 19](https://user-images.githubusercontent.com/13235519/41534840-519cef1a-7300-11e8-855b-b2cd6dbd0bc5.png)

**Comment by bogem** [comment]
Echodoc is shown only after you enter `(`. Sorry for bothering you
![screen shot 2018-06-18 at 14 05 57](https://user-images.githubusercontent.com/13235519/41534950-bf039f7c-7300-11e8-9b54-961e1781b1be.png)

**Comment by bogem** [comment]
It works also with `let g:nvim_typescript#max_completion_detail = 25`

**Comment by mhartington** [comment]
Glad to see you got this figured out!

**Comment by kinowarrior** [comment]
@mhartington - thanks for creating/supporting an awesome plugin. 

Be very grateful if you could [skim read this issue](https://github.com/Shougo/echodoc.vim/issues/68) and offer any thoughts. My current plugin settings are:

![nvim-typescript](https://user-images.githubusercontent.com/49199497/57124316-4cbb4300-6dc0-11e9-923f-65e564f923be.gif)

Currently, things look good initially but the moment I start typing the echodoc disappears, and I get no typing info. Other languages work as expected so I suspect this is an nvim-typescript specific setting issue.  Your thoughts would be greatly appreciated.

![nvim-typescript-2](https://user-images.githubusercontent.com/49199497/57124407-acb1e980-6dc0-11e9-9050-bfaf91dbf826.gif)

**Comment by kinowarrior** [comment]
Tried it with several different functions/libraries & get the same behaviour (just to be sure it wasn't due to limitations with a given omnicomplete signature availability etc).

![nvim-typescript-3](https://user-images.githubusercontent.com/49199497/57124737-cef83700-6dc1-11e9-9cb4-3d48b8404268.gif)
