### ISSUE TITLE
Enhancement request/question around allowing `preview_strategy` for the Preview methods?

### ISSUE THREAD

**Issue by megalithic** [mhartington/nvim-typescript#141]
# Enhancement request/question

Do you see value in allowing a `preview_strategy` param that could allow the user to define how they want splits to occur for `*Preview` methods? 

For instance, within this specific Preview method:
https://github.com/mhartington/nvim-typescript/blob/03ac69e18ccc51b457ccf55a9cecfd7a4231e2fc/rplugin/node/nvim_typescript/src/index.ts#L186
.. we could allow a param to say let the user define a `vsplit` instead of a horiz `split`.

If you don't think this is a negative-impact enhancement, I'd be happy to submit a PR.

## Environment Information

 * terminal: kitty
 * vim/nvim version: 0.3.0

**Comment by mhartington** [comment]
I dont think it's a bad idea to add. If you open up a PR, I'd gladly accept!

**Comment by mhartington** [comment]
Closing for now. If you're still up for it, please send a PR
