### ISSUE TITLE
[Question] trigger completions on interface fields

### ISSUE THREAD

**Issue by jeffwillette** [mhartington/nvim-typescript#145]
I always forget about the inner workings of deoplete and other vim plugins :( Is it possible to trigger completions when I am filling out an object of a type? When I am writing Go with deoplete I can trigger the omnifunc and it will show me the available fields.

Here is what it would look like in TS...

```
interface Foo {
  foo: string
  bar: string
}

const FooThing: Foo = {
  bar: 'bar',
  // trigger the completion with the cursor here and see that `foo` and `bar` are the available fields
}
```

**Comment by mhartington** [comment]
There's a few deoplete sources out there that will integrate with neosnippet to accomplish this. so it is possible. Just need to find the implementation to see how to do it

**Comment by moofish32** [comment]
bumping this topic again, we shouldn't need neosnippet right? If I type the first two letters autocomplete triggers, so the question is how to fire autocomplete properly in here?

**Comment by jeysal** [comment]
Similarly, completion inside of string literal unions also works, but only after typing 2 characters.

**Comment by moofish32** [comment]
I have actually moved to https://github.com/neoclide/coc.nvim to solve this problem. @mhartington this plugin is great and I'm happy to take this comment down if it offends you. The change to COC was not completely trivial, and I traded some code navigation habits (split open on goto def for example).

**Comment by jeysal** [comment]
@moofish32 Thanks for mentioning this, I'll take a look. I (and perhaps others who stumble over this) did in fact not know that plugin yet. Knowing alternatives is always a good thing IMO :)

**Comment by mhartington** [comment]
I guess I don't understand what it is you're trying achieve here. Just getting the properties to complete by  just entering a new line? Or by typing less than a few characters? I don't have any custom options set, but this is the default experience, which matches vscode.


![nvim-type-145](https://user-images.githubusercontent.com/2835826/57330660-b1d6a780-70e4-11e9-9c6e-c338e69cba58.gif)

**Comment by jeysal** [comment]
Hey @mhartington,
the reason I need this is because often times I
* have no idea what properties are available on the object expression, not even the first letter, or
* want to know which remaining properties that should be there I've missed.

Note that I wouldn't really mind if I have to trigger completion manually in this case (it doesn't need to open up automatically on a new line), but I didn't find any way to complete the available properties, even manually.

**Comment by mhartington** [comment]
> I don't understand what it is you're trying achieve here

Meaning I dont understand the desired results. 
Are you asking that if given 

```
interface Foo {
  foo: string
  bar: string
}

const fooThing: Foo = {_}
``` 
with my cursor at the `_`, when I hit enter, the completion should auto insert foo and bar? 

If that's the case, coc.nvim does not do this either (at least at quick glance).

**Comment by jeysal** [comment]
The key thing is just that unlike after at `someObject._`, in an object expression requires at least 2 characters before it completes a property name. It should not require entering a character, it be able to just show *all* available properties. At least to me, it does not matter whether this happens automatically or only after manually triggering completion.

**Comment by mhartington** [comment]
Something like this? 
![nvim-type-input-pattern](https://user-images.githubusercontent.com/2835826/57333572-30364800-70eb-11e9-8b52-a391e6da04e1.gif)

**Comment by jeysal** [comment]
Yes, exactly! Did you achieve this purely with configuration (if so, I didn't manage to) or did it require changes to the plugin code?

**Comment by mhartington** [comment]
This required modification to the deoplete input pattern regex, basically setting it to trigger on any and every input. There could be some performance issue here, but will test it out.
