### ISSUE TITLE
feat-diagnostic branch AsyncIterable

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#146]
I checked out the `feat-diagnostics` branch and got an error when building...

```
npm WARN neovim-test@1.0.0 No description
npm WARN neovim-test@1.0.0 No repository field.

audited 70 packages in 2.9s
found 0 vulnerabilities


> neovim-test@1.0.0 build /Users/Jeff/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript
> tsc --pretty -p tsconfig.json

../../../../../../../node_modules/@types/graphql/subscription/subscribe.d.ts:17:12 - error TS2304: Cannot find name 'AsyncIterator'.

17 ): Promise<AsyncIterator<ExecutionResult> | ExecutionResult>;
              ~~~~~~~~~~~~~


../../../../../../../node_modules/@types/graphql/subscription/subscribe.d.ts:29:12 - error TS2304: Cannot find name 'AsyncIterable'.

29 ): Promise<AsyncIterable<any>>;
              ~~~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! neovim-test@1.0.0 build: `tsc --pretty -p tsconfig.json`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the neovim-test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Jeff/.npm/_logs/2018-07-03T15_13_50_481Z-debug.log
```

I had to add `esnext.asynciterable` to the tsconfig.json lib array. Any idea why that would be?

**Comment by mhartington** [comment]
No idea where this is coming from, but `node_modules/@types/graphql` does seem fishy.
Not sure how to debug this, I just build/installed locally from scratch and wasn't able to replicate.

**Comment by deltaskelta** [comment]
I tried deleting `node_modules` and it still gave me the error.

Here is how I am running into the issue... I deleted the dir made by vim-plug, cloned the repo and checked out feat-diagnostics

```
cd ~/.config/nvim/plugged
git clone https://github.com/mhartington/nvim-typescript/issues/146
cd nvim_typescript
git checkout feat-diagnostics
./install.sh
```

**Comment by mhartington** [comment]
Still not able to replicate this. I just tried your instructions and was not able to replicate it.


<img width="1116" alt="screen shot 2018-07-04 at 1 23 51 pm" src="https://user-images.githubusercontent.com/2835826/42289436-81ef4c3c-7f8d-11e8-8768-ef4d6dfd95b8.png">

**Comment by deltaskelta** [comment]
well I definitely get the error, if all else is the same, it must be related to our node versions or OS...

```
NODE: v10.6.0
OS: OSSierra 10.13.5


tsc --version: Version 2.9.2
yarn info neovim: 4.2.0
```

since neovim and typescript are installed locally in the project, why does one need to install them globally like in the readme?

**Comment by mhartington** [comment]
Typescript globally is only needed if there is no local project install of typescript.
Neovim globally is needed to communicate from the neovim process and the plugin process

**Comment by deltaskelta** [comment]
hmm I just tried it in a docker container and the build worked without error.

Can I ask what OS you are on?

**Comment by mhartington** [comment]
mac OS 10.13

**Comment by deltaskelta** [comment]
can you also post your node, global tsc, and global neovim versions?

I am trying to track down what could be causing this weird behavior

**Comment by mhartington** [comment]
typescript global: 2.8.3
neovim global: 4.2.0
node: 8.9.1

Again, none of these packages have any dep of `@types/graphql`, that is coming from **your** project.
Is there anything symlinked with `npm link`? I'm out of ideas as to why this is happening. It's more of an issue with your environment than an issue with the plugin, otherwise there would be more reports. 

I'm going to close this. Please debug your environment.

**Comment by deltaskelta** [comment]
Oh yeah, I had a node_modules hiding in my home dir that was full of junk it collected. IDK how it got there, but I just deleted it and it started working as expected
