### ISSUE TITLE
change lib to esnext

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#147]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

`./install.sh` causes error according to the conversation in https://github.com/mhartington/nvim-typescript/issues/146

There was also a random issue in Apollo which caused the same error with typescript. https://github.com/apollographql/graphql-subscriptions/issues/83. Changing the lib to `esnext` should fix it and I don't think it will break anything else in this lib

I can make a PR if you think it is ok to change the lib to esnext

**Comment by mhartington** [comment]
I don't think this is actually needed. I have not run into any issues where esnext would be needed.
