### ISSUE TITLE
Function signature gets cropped

### ISSUE THREAD

**Issue by kornosaurus** [mhartington/nvim-typescript#148]
# Problems summary
Currently when completing functions the function signature is shown in the menu, if the signature is too long this will get cropped in the middle and `...` is added, this gives us a signature like this `Console.warn(message? an.. any[]): void`

Which is fine I guess, the problem (for me atleast) comes when either echodoc shows up and also has this clipped function signature or when im expanding the function parameters with neosnippet, i feel both of these are unusable like this.

## Expected
Getting the full signature so that echodoc/neosnippet and etc works.

## Environment Information

 * terminal: alacritty
 * vim/nvim version: 0.2.2

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Just to get Plug. Not relevant to the issue
if empty(glob('~/.config/nvim/autoload/plug.vim'))
silent !curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin()
function! DoRemote(arg)
  UpdateRemotePlugins
endfunction
" Actual configuration
Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') } " Autocompletion
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript'
Plug 'Shougo/echodoc.vim'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:echodoc_enable_at_startup = 1
let g:nvim_typescript#max_completion_detail=100

let g:echodoc_enable_at_startup = 1
set laststatus=2
set noshowmode

```

## The reproduce ways from neovim starting

1. type `console.w`
2. see signature of `console.warn`

## Screen shot (if possible)
1. in completion menu
![2018-07-06-133347_1024x768_scrot](https://user-images.githubusercontent.com/10253840/42376948-64226f96-8121-11e8-8917-f95b65b0b0f6.png)

2. echodoc
![2018-07-06-133401_1024x768_scrot](https://user-images.githubusercontent.com/10253840/42376953-66c10244-8121-11e8-8eb5-8101e85a2001.png)

**Comment by mhartington** [comment]
Should be an easy fix

**Comment by mhartington** [comment]
Looks like deoplete has some options that truncates the completion items text.
