### ISSUE TITLE
update to allow typescript 2.9

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#150]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

let g:nvim_typescript#ts_version shows 2.4.0

## Expected

to see the current version of 2.9.x

I'm not sure if this is just out of date or if it really requires 2.4.0. Is there anything that needs to be updated to allow for 2.9.x?

**Comment by mhartington** [comment]
Heh, forgot about that variable. It's not really needed, so you can just ignore it for now. I'll remove it for now
