### ISSUE TITLE
Using LSP's range to define better text objects in Neovim

### ISSUE THREAD

**Issue by snoblenet** [mhartington/nvim-typescript#151]
Language Servers can return a range (line and character number from the start of the function to the end). I'm wondering if this can be used to define better text objects in Neovim -- i.e. for sort inside function, jump to start of next function, etc etc.

**Comment by mhartington** [comment]
This could be a good option to add a similar Text Range object to the node-client. As the TSServer returns most of this data, so it should be possible to pass line numbers and columns. Would make all the text edits this needs to make easier. Happy to accept a PR to node-client

**Comment by mhartington** [comment]
Closing as not really an issue with the plugin, but a feature request for node-client.
