### ISSUE TITLE
stops showing errors on insertleave when switching back and forth between buffers

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#154]
# Problems summary

I have been noticing that after a while the plugin just stops working while switching back and forth between buffers. It just freezes and stops adding or removing errors to the quickfix window.

## Expected

the plugin keeps checking for errors

## Environment Information

 * terminal: iterm2
 * vim/nvim version: NVIM v0.3.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'mhartington/nvim-typescript'

call plug#end()

let g:python_host_prog = '/Users/Jeff/.virtualenvs/neovim2/bin/python'
let g:python3_host_prog = '/Users/Jeff/.virtualenvs/neovim/bin/python'
let g:node_host_prog = '/usr/local/bin/neovim-node-host'
let g:ruby_host_prog = '/usr/local/bin/neovim-ruby-host'
let $NVIM_NODE_LOG_FILE='/tmp/nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='debug'

let g:deoplete#enable_at_startup = 1

augroup typescript
    autocmd!
    " setting typescript things.
    let g:nvim_typescript#type_info_on_hold = 1
    let g:nvim_typescript#signature_complete = 1

    autocmd BufNewFile,BufRead *.ts set filetype=typescript
    autocmd BufNewFile,BufRead *.tsx set filetype=typescript.jsx
    autocmd FileType typescript set tabstop=2 shiftwidth=2 expandtab
    nnoremap <leader>i :TSImport<CR>
    nnoremap <leader>d :TSDefPreview<CR>
    nnoremap <leader>t :TSType<CR>
    nnoremap <leader>f :TSGetCodeFix<CR> " this is called on insert leave
augroup END
```

## The reproduce ways from neovim starting

 1. clone example repo git@github.com:deltaskelta/nvim_typescript-crash.git
 2. use init.vim above
 3. cd into repo
 4. $ vim
 5. :badd index.ts
 6. write some functions that are guaranteed to throw an error like `const a = (b) => console.log(b)`
 7. :badd foo.ts
 7.5 EDIT: do a `:copen` sometime to see the errors in the quickfix window 
 8. :bnext!
 9. write function guaranteed to cause error
 10. :bnext!
 11. keep switching and writing functions to throw error

Sometimes the freeze happens very quickly, sometimes it takes 6-7 switches back and forth writing new functions that are guaranteed to throw errors into the gutter. 

## Screen shot (if possible)

![screen shot 2018-07-11 at 11 57 10 pm](https://user-images.githubusercontent.com/9424192/42580754-35a9b928-8566-11e8-9a42-a6610dfa6a63.png)

**Comment by mhartington** [comment]
Not able to replicate this issues. I'd gladly accept a PR to change the diagnostics behavior though.

**Comment by deltaskelta** [comment]
Could you be more specific? If you can't replicate the issue and everything is fine, then why would the diagnostics behavior need to be changed?

**Comment by mhartington** [comment]
The current autocmnds being used are not ideal, and it would be nicer to use the buffer update api. This could allot for a much more optimized watcher 

Mike Hartington

**Comment by deltaskelta** [comment]
I am still getting the error. Is there a series of commands I can put into a function in order to restart the plugin from inside of vim? I really hate having to close it all the time and reopen it without all of the buffers that I was working on. 

I have tried doing :TSStop :TSStart :TSReloadProject but that did not work for me...
