### ISSUE TITLE
error sign stays in the gutter

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#155]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

error sign stays in the gutter after error is corrected

## Expected

it should go away

## Environment Information

 * terminal: iterm2
 * vim/nvim version: NVIM v0.3.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'mhartington/nvim-typescript'

call plug#end()

" TODO: this might not work on a remote machine
let g:python_host_prog = '/Users/Jeff/.virtualenvs/neovim2/bin/python'
let g:python3_host_prog = '/Users/Jeff/.virtualenvs/neovim/bin/python'
let g:node_host_prog = '/usr/local/bin/neovim-node-host'
let g:ruby_host_prog = '/usr/local/bin/neovim-ruby-host'
let $NVIM_NODE_LOG_FILE='/tmp/nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='debug'

let g:deoplete#enable_at_startup = 1

augroup typescript
    autocmd!
    " setting typescript things.
    let g:nvim_typescript#type_info_on_hold = 1
    let g:nvim_typescript#signature_complete = 1

    autocmd BufNewFile,BufRead *.ts set filetype=typescript
    autocmd BufNewFile,BufRead *.tsx set filetype=typescript.jsx
    autocmd FileType typescript set tabstop=2 shiftwidth=2 expandtab
    nnoremap <leader>i :TSImport<CR>
    nnoremap <leader>d :TSDefPreview<CR>
    nnoremap <leader>t :TSType<CR>
    nnoremap <leader>f :TSGetCodeFix<CR> " this is called on insert leave
augroup END
```

## The reproduce ways from neovim starting

 1. clone repo git@github.com:deltaskelta/nvim_typescript-crash.git
 2. cd into repo
 3. vim -u init.vim foo.ts
 4. fix the error that comes up by giving the arg a type
 5. see that the error stays there

## Example project repo?

git@github.com:deltaskelta/nvim_typescript-crash.git

## Screen shot (if possible)

error cleared from qf window but still present in the gutter

![screen shot 2018-07-12 at 10 56 45 am](https://user-images.githubusercontent.com/9424192/42608362-4de8e318-85c2-11e8-930a-28fac1e951e4.png)

**Comment by mhartington** [comment]
![issue-155](https://user-images.githubusercontent.com/2835826/42652790-1e0dd380-85d9-11e8-96b7-286f84017a27.gif)

I clone your sample project and was not able to replicate the error. I have seen it happen, but not often. Need to revisit how signs are set/stored/cleared and make sure the async stuff is happening correctly.

**Comment by deltaskelta** [comment]
The commit looks like it got me halfway there. I was getting close to 0% of the errors removed from the gutter before. I now get about 50% of them removed. I am trying to track down the exact situations where they stay there and I will give an example in the nvim docker setup

**Comment by mhartington** [comment]
another tip is to also use node-clients debug flag

```
 let $NVIM_NODE_HOST_DEBUG=1
```

Then debug the code through Chrome Canary's devtools

**Comment by jaapz** [comment]
Just want to chime in and say I'm experiencing the same bug. At first the dots in the gutter are removed correctly but after a while the dots hang around, even when the lines they were meant for are removed. The error in the line itself will often not be marked by underline anymore (but sometimes it will), when it is fixed.

**Comment by djwelch** [comment]
Just to say I was having this issue all the time, ie errors would almost never go away.  Now this fix seems much better and errors do go away, although I haven't programmed in typescript in anger much so far.  I did update all plugins, including deoplete.

**Comment by niklaas** [comment]
Having the same issue. I'm just testing to deactivate that all at once with the following declaration:

```
let g:nvim_typescript#default_signs = get(g:, 'nvim_typescript#default_signs', [])
```

I'm not sure whether that's the right way to do so though. Looking at https://github.com/mhartington/nvim-typescript/blob/faea2f63b034848330acb393f359f2b894bfe956/plugin/nvim_typescript.vim#L72-L98 I came up with that.

I don't need the signs because w0rp/ale does linting for me.

**Comment by mhartington** [comment]
@niklaas yeah, the correct way to disable diagnostics through this plugin is by setting 

```
let g:nvim_typescript#diagnosticsEnable  = 0
```

**Comment by bolstycjw** [comment]
@mhartington Tried disabling the diagnostics through g:nvim_typescript#diagnosticsEnable. But errors are still displayed.

**Comment by mhartington** [comment]
```
let g:nvim_typescript#diagnosticsEnable=0
````

@bolstycjw Not seeing this in my setup, seems to be working when the variable is set to 0.

**Comment by jaapz** [comment]
The bug reported in this issue still happens for me. Setting `diagnosticsEnable` to 0 just disables the entire feature, which I'd still like to use...

**Comment by half0wl** [comment]
I just ran into a similar issue caused by `nvim-typescript` and `ale` fighting in the gutter. Heads up for anyone stumbling in here from Google, etc. - if you want to disable diagnostics, the comments above are no longer accurate after #178:

```
let g:nvim_typescript#diagnosticsEnable=0
```

should be

```
let g:nvim_typescript#diagnostics_enable=0
```

i.e. snake_case instead of camelCase.
