### ISSUE TITLE
Import does not work on JSX symbols

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#157]
# Problems summary

The import seems to not be compatible with JSX symbols. What needs to be done in order to get this working?

**Comment by deltaskelta** [comment]
hmm strange, I must have tried 100 times before to import JSX and it never did and now it just did it once for the first time. Do you know the current state of JSX support?

**Comment by mhartington** [comment]
Per the issue template, I need more information. A sample project would help debug if there are any potential issues. Also, test in VSCode, as this plugin uses the same process to search and apply imports.

Closing as issues template was not followed.
