### ISSUE TITLE
extreme lag on first completion + diagnostics failing

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#158]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

This conatinerized neovim showcases what I have been experiencing with extreme lag on the first completion and tsserver stopping or at least the diagnostics become unresponsive.

## Expected

No blocking of the editor and tsserver 

## Environment Information

 * terminal: iterm2
 * vim/nvim version: NVIM v0.3.0

## Provide a minimal vim rc with less than 50 lines (Required!)

vimrc is in repro repo

## The reproduce ways from neovim starting

 1. follow repo setup instructions from repo below
 2. edit the file src/index.ts
 3. add function guaranteed to cause error and fix the error, add a few more if needed

## Example project repo?

https://github.com/deltaskelta/nvim-typescript-docker

## Screen shot (if possible)

EDIT: In this shot you can see there are no errors, but the errors remain in the qf and in the gutter. which means diagnostics are unresponsive

![screen shot 2018-07-13 at 2 13 28 pm](https://user-images.githubusercontent.com/9424192/42673556-03b524e2-86a7-11e8-9550-e88144d5be7f.png)

**Comment by deltaskelta** [comment]
On another note, my docker repo would be a good way to ensure people can replicate errors across environments. Its really a bummer to put time into a repro and then have the issue closed because it can't be replicated. Let me know what you think

**Comment by mhartington** [comment]
This docker setup is GREAT! Thank you so much for putting this together, I was able to figure out what the issue is. Seems to be an issue on two parts.

### Deoplete delay time
Deoplete has a delay option for completion, in my local setup, I have this set to 0, so there is not delay.

```viml
  let g:deoplete#auto_complete_delay = 0
```

### Server start up time

Seems the node process is taking a bit to start causing the huge lag you're describing. 
I'll have to look into some ways to deal with that

**Comment by deltaskelta** [comment]
I tried out the deoplete option and I am still getting the lag because I think it is still blocking on the server starting. It is possible that the server just takes a while to start which is ok, but is there a way to make it not block the editor while it is starting?

**Comment by DonnieWest** [comment]
I haven't been successful in the past with getting deoplete to not block on startup. There are some workarounds but they end up just blocking your editor later

This plugin does support nvim completion manager, but that project is deprecated and the successor ncm2 isn't supported yet, but neither have the blocking issue because of how they are architected. It's a bit early for ncm2, otherwise I'd try to throw together support for it :-)

**Comment by deltaskelta** [comment]
I see. I guess its not changeable then. It wouldn't be so bad if it was a one time startup and I didn't have to restart vim all the time. I have another issue with `nvim_typescript` becoming unresponsive that I am trying to reproduce which makes me restart it all the time and go through the `tsserver` startup blocking often.

**Comment by mhartington** [comment]
As for the extreme lag at startups I’m wondering if yarn could be the issue. I notice the docker container uses yarn and I use npm. Have you tested?

**Comment by deltaskelta** [comment]
The latest commit in the docker repo uses npm in the setup shell script.
Still have the issue

**Comment by mhartington** [comment]
I changed how deoplete completion works. Can you pull the latest and run `UpdateRemotePlugin`

**Comment by deltaskelta** [comment]
This update seems great. So far I have not experienced the big lag and it seems that I don't have to restart vim anymore either. 

It does seem like the same (error?) is happening, but it somehow recovers after a second and runs the diagnostics again. The output of my recent messages looks like this
```
:mes
```
![screen shot 2018-07-17 at 12 03 20 am](https://user-images.githubusercontent.com/9424192/42766384-504d1700-8955-11e8-83d6-854685049ced.png)

**Comment by mhartington** [comment]
Not sure what this is. I will add that the docker image is acting funny for me. Completion does not show for me and everything is slightly sluggish. I'm testing in a real set and the plugin is very fast for me.

**Comment by deltaskelta** [comment]
I believe the sluggishness might be caused by the fact that there is a slowness when mounting filesystems from mac to docker since it has to convert the fs https://docs.docker.com/docker-for-mac/osxfs-caching/

It may be coming from somewhere else though, I am not sure.

Completion does not show on the latest `nvim_typescript`? or always since you have tried it?

**Comment by mhartington** [comment]
I have this as a test repo, with variables files and libs for testing imports and diagnostics.

https://github.com/mhartington/nvim-typescript-playground


Use this instead please.
