### ISSUE TITLE
Turn off syntax checking?

### ISSUE THREAD

**Issue by dakom** [mhartington/nvim-typescript#164]
I am using this plugin mostly for providing type completion to deoplete, and ALE is running for runtime syntax checks.

Is there a way to turn _off_ the syntax checks from this plugin, so that it won't waste resources or conflict with ALE?

Great work btw - love all the extra stuff the type completion is giving me (e.g. html props etc.)

**Comment by kswope** [comment]
Same.    It seems that nothing plays nice with ALE.  I just came over from YouCompleteMe and that is also fighting in the gutter with ALE.

**Comment by iovis9** [comment]
Same with Neomake. Also it's overwriting whatever there is in the QuickFix window on every exit insert mode, which is very annoying.

**Comment by pyrho** [comment]
Try adding `let g:nvim_typescript#diagnosticsEnable = 0` to your .vimrc.

**Comment by mhartington** [comment]
Sorry, been busy with work and life. Yeah, you can disable diagnostics using that option. Added it but i think I forgot to document it

**Comment by ohcibi** [comment]
Its `diagnostic_enable` according to the docs.
