### ISSUE TITLE
(Feature) Option to use either quickfix or location list

### ISSUE THREAD

**Issue by joerideg** [mhartington/nvim-typescript#173]
Hi, 
First of all thanks for your work on this awesome plugin.
There is only 1 feature I'm missing and that is choosing between quickfix and location list to populate with TSRefs.

I saw this issue: https://github.com/mhartington/nvim-typescript/pull/51
I would like to make the case that using the location list does not always work nicely in combination with other plugins, for example Ale Linter. 

Having the option to choose to use either quicklist or location list would give some flexibility to end users which might have different use cases to use either of the two. 

cheers

**Comment by mhartington** [comment]
at the moment, I'm keeping diagnostics to loclist and tsrefs to quickfix.
