### ISSUE TITLE
Option to disable diagnostics

### ISSUE THREAD

**Issue by bogem** [mhartington/nvim-typescript#174]
I spend a lot of time to find some information about how to disable diagnostics in `nvim-typescript` or in `deoplete`. Is there any option for it? I want to use alternative plugin (ALE) for linting.

**Comment by mhartington** [comment]
\ get(g:, 'nvim_typescript#diagnosticsEnable', 1)

**Comment by bogem** [comment]
Thank you!

**Comment by tribou** [comment]
Permalink: https://github.com/mhartington/nvim-typescript/blob/eca2bb92d45f09fc500317ededace5bc849063c1/plugin/nvim_typescript.vim#L34:L35
