### ISSUE TITLE
Navigation to the previous buffer (like ctrl+t in other plugins)

### ISSUE THREAD

**Issue by leoluz** [mhartington/nvim-typescript#182]
# Problems summary
I checked the documentation and couldn't find a way to configure the plugin to go back to the previous buffer after doing `:TSDef`

## Expected
It would be great to be able to go back to the previous buffer after doing `:TSDef`. Is there a way to achieve a similar behaviour as we have with `ctrl+t` in other plugins?

## Environment Information

```
NVIM v0.3.0
Build type: Release
LuaJIT 2.0.5
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
...

" Typescript plugins
call dein#add('HerringtonDarkholme/yats.vim')
call dein#add('mhartington/nvim-typescript', {'build': './install.sh'})

...

let g:nvim_typescript#default_mappings = 1

...
```

**Comment by DannyDelott** [comment]
Would also love to know how to navigate back to the previous buffer after running `:TSDef`..

**Comment by mhartington** [comment]
You can also use `:bnext` or `:bprevious` to navigate back.
