### ISSUE TITLE
Refactor across files not working

### ISSUE THREAD

**Issue by kaihendry** [mhartington/nvim-typescript#184]
https://github.com/kaihendry/dotfiles/blob/master/.config/nvim/init.vim
https://s.natalian.org/2018-09-27/nvim-tsc.mp4

# Problems summary

Sorry, I am new to tsc. Am I expected to run :TSstart on startup?

## Expected

Can :TSRename across files

## Environment Information

 * Archlinux - everything uptodate at time of writing

**Comment by mhartington** [comment]
Hello! 

> Am I expected to run :TSstart on startup?

No, this should be started right away.  Looking at the video, you're opening a regular JavaScript file vs a TypeScript file. To enable JavaScript support, you must set `g:nvim_typescript#javascript_support` to 1. Please see `:h g:nvim_typescript#javascript_support`


Once this is setup, symbol rename should happen.

**Comment by kaihendry** [comment]
Thanks, TSrename works... but only on the current open file. Yes, the project I am working on has a jsconfig:
https://github.com/unee-t/frontend/blob/master/jsconfig.json
