### ISSUE TITLE
Jump to def broken on React components

### ISSUE THREAD

**Issue by ryanbas21** [mhartington/nvim-typescript#188]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
If you try to jump to def on a react component that is typed like

```
const ReactComponentName : React.SFC<{}> = ( <div /> )
```

jump to def will go to the react type definitions. This is a common way to type functional components in react, and its the only pain point I have.

`gd` will go to the import (as  expected).
![typescript](https://user-images.githubusercontent.com/18267769/46239084-398f5300-c359-11e8-9853-f56b8125c37d.gif)

## Expected

It would be swell if it could jump to the actual component definition
## Environment Information
nvim - iterm 2

 * terminal:
 * vim/nvim version:

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/nvim-typescript
call plug#begin('~/.vim/plugged')
Plug 'mhartington/nvim-typescript', {'for': ['typescript', 'tsx'], 'do': 'sh ./install.sh' }
Plug 'leafgarland/typescript-vim', { 'for': ['typescript', 'tsx'] }
call plug#end()
```

## The reproduce ways from neovim starting

Open react app - type functional component like above - try to jump to def.

## Example project repo?

Most common errors are related to a project not being set up correctly.
Please provid a minimal project example to reduce back-and-forth time.
This makes debugging MUCH easier

**Comment by mhartington** [comment]
So i tried this out and wasn't able to replicate the error your seeing. 

![react-ts-def](https://user-images.githubusercontent.com/2835826/46585957-a8e60080-ca45-11e8-855d-69fd12e5ce52.gif)


This is using yats.vim for syntax, but that shouldn't matter that much.

**Comment by ryanbas21** [comment]
hm, it happens to me at work and at home but only on components that are typed like that. if a component isn't typed like that then it works as expected.

I am using typescript-vim, but as you said I wouldn't suspect that to be the problem

**Comment by mhartington** [comment]
Mind making a small sample project? This really helps debugging these types of issues.

**Comment by ryanbas21** [comment]
@mhartington I just threw something together on my work computer and I didn't experience the bug.

Which of course makes me wonder if its something in my TS configs that i'm including?

I'm not an expert in TS but is there a flag I should look for in my setups that could be a culprit?

I used https://www.npmjs.com/package/react-scripts-ts to spin up a sample project and it worked fine. But for example in my work repo, which is much much larger, I have the issue described above.

**Comment by mhartington** [comment]
Used the react-scripts-ts version to create a new project. I would checkout the tsconfig.json in the sample project and see whats up. Going to close since this is not an issue with the plugin, but a project setup.

**Comment by ryanbas21** [comment]
So sorry to reopen this, but i've copy and pasted the tsconfig from CRA and another TS project (where the bug doesn't exist), and I haven't been able to pin point out what the issue is or what the conflict is.

I think this would be worthwhile to investigate as we can determine what could potentially be making the plugin jump to the type.

I tried messing with the includes / excludes that you can set in the tsconfig and didn't find that to matter.

I don't know what setting could trigger this

**Comment by mhartington** [comment]
The gif is too fast to see what is happening and the repo you sent me does not have a tsconfig.json. Please provide **clear** instructions on how to reproduce this error.

**Comment by ryanbas21** [comment]
@mhartington My apologies. there is a typescript branch 
https://github.com/ryanbas21/crypto-portfolio/tree/ts

I copy and pasted the tsconfig.json into a second project, where the jump to definition was not working and I ended up with the same result (a gatsby project ).

working:
![working](https://user-images.githubusercontent.com/18267769/46773980-c32e1180-ccc5-11e8-8746-9cb2db6703e9.gif)



I am not nearly an expert in vim. I am just trying to debug, and I appreciate the time you've taken thus far.

It just seems to me, that using identical tsconfigs don't solve the issue.

So - steps I am taking to reproduce

Working example:
1. Go to src/navbar/index.tsx (on ts branch)
2. Place cursor on line 44 on the NavbarItem component.
3. Jump to definition

Not working example:
https://github.com/ryanbas21/ryan_blog (can use develop branch)

1. Go to src/components/card/index.tsx
2. Place cursor on line 70.
3. `TSDef`

![not](https://user-images.githubusercontent.com/18267769/46774149-86164f00-ccc6-11e8-89ef-6f7939cd3c1b.gif)
