### ISSUE TITLE
Errors now clear out quickfix list

### ISSUE THREAD

**Issue by mattaschmann** [mhartington/nvim-typescript#190]
Commit #12ad068b4e0abf96cec27d6801c879a1b98b145a changed from using the Location List to using the Quickfix List for errors.  This is not ideal as I often use the Quickfix List for search results, and this will get cleared out if I make any changes to my typescript files.  Perhaps we could have an option to disable this feature (as some of us might use a different option, like ALE), or to choose to use the Location List?

**Comment by mhartington** [comment]
This should be fixed. Errors get populated to loclists, and everything else goes to quick-fix

**Comment by mattaschmann** [comment]
Works great, thanks!
