### ISSUE TITLE
Is it possible to use sources from external modules?

### ISSUE THREAD

**Issue by jorgeOmurillo** [mhartington/nvim-typescript#193]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
I've installed nvim-typescript and it works well, the server starts normally and autocompletion is available.
But when working on a file (app.js) and after `import Foo from 'Bar';`, is it possible for the autocomplete to list all available modules for `Foo`?

Currently, `Foo.` doesn't bring up any results.
My folder structure is:
```
project/
          node_modules/
               Bar.js
          src/
               app.js
```

Should I set Deoplete to use custom sources for this to work?

## Environment Information

 * terminal: iTerm2
 * vim/nvim version: nvim 0.3.1

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/nvim-typescript
```

## The reproduce ways from neovim starting

 1. foo
 2. bar
 3. baz

## Example project repo?

Most common errors are related to a project not being set up correctly.
Please provid a minimal project example to reduce back-and-forth time.
This makes debugging MUCH easier

**Comment by mhartington** [comment]
This is supported. If the module provides types, TSServer will autocomplete what is available. If the module does not provide it's own types, you need to install the types from npm.
