### ISSUE TITLE
Error detected while processing FileType Auto Commands for "typescript"

### ISSUE THREAD

**Issue by Edhebi** [mhartington/nvim-typescript#197]
# Problems summary
When opening any `.ts` file, I get the following error:
```
Error detected while processing FileType Auto Commands for "typescript"
E117: Unknown Function: TSOnBufEnter
E492: Unknown Command : TSGetDiagnostics
Error detected whille processing TextChanged Auto Commands for "*.ts" :
E492: Unknow Command: TSGetDiagnostics
```
Note: that message was translated from french, so I reused the english version from other issues and edited content.

Before you ask, I did try to run ìnstall.sh manualy` and I did `UpdateRemotePlugins`, nothing changed.

## Expected
No error

## Environment Information

 * terminal: terminal MATE
 * nvim `:version`:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=
gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/n
eovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compilé par builduser

Features: +acl +iconv +jemalloc +tui
```
distribution: archlinux x86_64, kernel 4.18.16, (2018-10-05)

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set nocompatible

set runtimepath+=~/.local/share/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.local/share/dein')
    call dein#begin('~/.local/share/dein')
    call dein#add('~/.local/share/dein')

	call dein#add('HerringtonDarkholme/yats')
	call dein#add('mhartington/nvim-typescript', { 'do': './install.sh'})

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif

filetype plugin indent on
```
edit: removed irrelevant `vim-devicons`

## The reproduce ways from neovim starting

 1. `nvim anyfile.ts`

## Screenshot
![image](https://user-images.githubusercontent.com/19776499/48008756-90d3d080-e11a-11e8-8d68-d7c6b3d77083.png)

**Comment by cifkle** [comment]
Isn't it `{ 'build': './install.sh' }` for dein? You have `{ 'do': './install.sh' }`

I had the same problem, but after running `:UpdateRemotePlugins` it started to work. Try removing and reinstalling the plugin. Sorry, I don't use Dein I use vim-plug but I think that shouldn't be the issue.

**Comment by HaleTom** [comment]
I get the same, using `NeoBundle`.

```
Error detected while processing FileType Auto commands for "typescript":        
E117: Unknown function: TSOnBufEnter                                            
E492: Not an editor command: TSGetDiagnostics                                   
Press ENTER or type command to continue
```

Then:

```
Error detected while processing CursorMoved Auto commands for "*.ts":           
E117: Unknown function: TSEchoMessage                                           
Press ENTER or type command to continue
```

Then

```
Error detected while processing TextChanged Auto commands for "*.ts":           
E492: Not an editor command: TSGetDiagnostics                                   
Press ENTER or type command to continue
```

**Comment by cifkle** [comment]
Here are a couple of things you could check to see if everything is correctly installed inside `nvim`:
1. Run `:checkhealth`, see if python and npm plugins are installed for neovim
2. Run `:h nvim-typescript` and see if that opens up the documentation (You could also check the FAQ to help troubleshoot your problem there)
3. On another terminal, run `which tsc` to see if typescript is installed globally or `npm ls -g --depth=0`
4. Optionally, you should install deoplete and see if that helps, since I use deoplete

**Comment by Edhebi** [comment]
- python3, python3, and node providers are all available
- the documentation works
- tsc is globally installed
- having deoplete doesn't cnange anything

I would gladly send any log or file you want. I've no idea where your FAQ is tho ... :/
On a sidenote, my only globally installed npm packages are `typescript` and `neovim`, do I need anything else ?

**Comment by Edhebi** [comment]
Side note, where you able to reproduce ?

**Comment by cifkle** [comment]
> I would gladly send any log or file you want. I've no idea where your FAQ is tho ... :/

Sorry, I meant troubleshoot is in the documentation. 

> On a sidenote, my only globally installed npm packages are `typescript` and `neovim`, do I need anything else ?

No, you don't need anything else. I'm not sure what exactly is the problem, I'm thinking neovim doesn't have the paths set correctly for nvim-typescript or it's not able to find the correct location of the call.

**Comment by cifkle** [comment]
> Side note, where you able to reproduce ?

I'm not sure what you mean by that.

**Comment by mhartington** [comment]
Hey there! I’m traveling at the moment, so I’ll take a look when I can

**Comment by ilkka** [comment]
I have the same problem, with essentially the same minimal vimrc as the OP, and as extra info I've tried this in neovim 0.3.1 on Win10 and Ubuntu on Windows, with identical results. Health check all green, remote plugins updated, install script run.

**Comment by ilkka** [comment]
Okay, I think I managed to get a handle on why I had this problem. I was running `npm i && npm run build` in the `nvim_typescript` directory that was under my `<dein basedir>/repos` hierarchy. However, the rplugin was actually being registered from `<dein basedir>\.cache\init.vim\.dein\rplugin\node\nvim_typescript`, where it apparently was being copied by `dein#install()`. When I ran `npm i && npm run build` in _there_, instead, there are no errors when I open TS files and I get the message about the server starting.

**Comment by herman-rogers** [comment]
Hmm having these exact issues on Mac. Everything in CheckHealth is green and I have all of the requirements, so not sure what's causing the issue. Afaik it should be working at this point.

**Comment by Edhebi** [comment]
Update: made it work by running `install.as` at `<dein>/.cache/init.vim/.dein/install.sh`. My current supposition is :
- `dein` works by creating one big fake plugin (`.cache/init.vim/)`, and merging every plugin inside it.
- it correctly runs the `install.sh` script, but doesn't merge the `node_modules/` directory, as it doesn't detects updates in the plugin directory.

Note: The simplest fix that would survive updates would probably be to symlink everything. What are the files created by `install.sh` that I need to keep track of, other that `node_modules` ?

I'm closing the issue as it seems to be a problem with dein rather than `nvim_typescript`...

**Comment by brozorec** [comment]
I got the same issue but made it work by installing `Plug 'HerringtonDarkholme/yats.vim'`

**Comment by pyrho** [comment]
The README file mentions:

>  " Dein
># REQUIRED: Add a syntax file. YATS is the best
>call dein#add('HerringtonDarkholme/yats.vim')
>call dein#add('mhartington/nvim-typescript', {'build': './install.sh'})

**Comment by psxvoid** [comment]
For me on windows 10 (using powershell) this error was caused because dein wasn't be able to run sh script. Essentially, it can be resolved by:

1. go to nvim-typescript plugin directory (`.cache\dein\repos\github.com\mhartington\nvim-typescript\`)
2. go to `rplugin\node\nvim_typescript` AND open powershell in that folder
3. run `npm install` and `npm run build`
4. open nvim and run `:UpdateRemotePlugins`

Now it works (at least for me)!

**Comment by michaeltintiuc** [comment]
I had to do the same on a linux machine using `Plug`, thanks @psxvoid !

**Comment by maotora** [comment]
@psxvoid when I run `npm run build` I get these errors...


```
> neovim-test@1.0.0 build /home/user/bin/bin/my-dotfiles/.vim/bundle/nvim-typescript/rplugin/node/nvim_typescript
> tsc --pretty -p tsconfig.json

../../../../../../../../../node_modules/jest-diff/build/diffLines.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DiffOptions } from './types';
              ~

../../../../../../../../../node_modules/jest-diff/build/diffLines.d.ts:8:34 - error TS1005: ';' expected.

8 import type { DiffOptions } from './types';
                                   ~~~~~~~~~

../../../../../../../../../node_modules/jest-diff/build/index.d.ts:10:13 - error TS1005: '=' expected.

10 import type { DiffOptions } from './types';
               ~

../../../../../../../../../node_modules/jest-diff/build/index.d.ts:10:34 - error TS1005: ';' expected.

10 import type { DiffOptions } from './types';
                                    ~~~~~~~~~

../../../../../../../../../node_modules/jest-diff/build/index.d.ts:11:1 - error TS1128: Declaration or statement expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
   ~~~~~~

../../../../../../../../../node_modules/jest-diff/build/index.d.ts:11:13 - error TS1005: ';' expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
               ~

../../../../../../../../../node_modules/jest-diff/build/index.d.ts:11:52 - error TS1005: ';' expected.

11 export type { DiffOptions, DiffOptionsColor } from './types';
                                                      ~~~~~~~~~

../../../../../../../../../node_modules/jest-diff/build/printDiffs.d.ts:8:13 - error TS1005: '=' expected.

8 import type { DiffOptions, DiffOptionsNormalized } from './types';
              ~

../../../../../../../../../node_modules/jest-diff/build/printDiffs.d.ts:8:57 - error TS1005: ';' expected.

8 import type { DiffOptions, DiffOptionsNormalized } from './types';
                                                          ~~~~~~~~~

../../../../../../../../../node_modules/pretty-format/build/index.d.ts:7:13 - error TS1005: '=' expected.

7 import type * as PrettyFormat from './types';
              ~

../../../../../../../../../node_modules/pretty-format/build/index.d.ts:7:18 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                   ~~~~~~~~~~~~

../../../../../../../../../node_modules/pretty-format/build/index.d.ts:7:31 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                                ~~~~

../../../../../../../../../node_modules/pretty-format/build/index.d.ts:7:36 - error TS1005: ';' expected.

7 import type * as PrettyFormat from './types';
                                     ~~~~~~~~~


Found 13 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! neovim-test@1.0.0 build: `tsc --pretty -p tsconfig.json`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the neovim-test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-25T09_04_28_674Z-debug.log

```

**Comment by psxvoid** [comment]
> @psxvoid when I run `npm run build` I get these errors...

Which version of nodejs are you using? Do the same errors appear in nodejs `v14.15.1`?

**Comment by maotora** [comment]
@psxvoid I was using v12 I just upgraded to v14.16.0 have not experienced the issue until now.

Thank you!
