### ISSUE TITLE
:TSRename across multiple files

### ISSUE THREAD

**Issue by williamboman** [mhartington/nvim-typescript#198]
Hey! Thanks for this awesome plugin :).

I'm not really understanding how `:TSRename` should behave when changing across multiple files. Right now it sort of opens buffers, where the rename operation should take place, in rapid succession and finally ends up in the last buffer where the rename operation should happen. However - only this last file will actually have the rename operation applied to it, the previous buffers will not be changed at all (unless it's open in another pane/window). Have I misconfigured something or is this WAI?

Thanks!

**Comment by mhartington** [comment]
Hey there! So this typically should work without an issue, but I have see some cases were the symbol is not renamed. It seems to be a limitation with TSServer and not being able to resolve the symbol

**Comment by williamboman** [comment]
I see. So should the `:TSRename` operation automatically write all files it changes?

**Comment by mhartington** [comment]
It does not automatically write the changes to disk (to mimic vscode's behaviour) The buffers should still be in memory if you have `set hidden` in your init.vim, and you can access them by using `:bn` and `:bp`.

**Comment by williamboman** [comment]
Ah I see! Is it somehow possible to see all files that were changed, like in a location list?

**Comment by mhartington** [comment]
A location list should be provided now. Closing!

**Comment by williamboman** [comment]
I noticed earlier, 💯💯

**Comment by daliusd** [comment]
TSRename is not working if you are not using "set hidden". Is it possible to use "tabe ${defFile}" instead of "e! ${defFile}" in hidden is not set?
