### ISSUE TITLE
How to troubleshot my specific problem

### ISSUE THREAD

**Issue by stavenko** [mhartington/nvim-typescript#206]
Hello!
In my company we use really sophisticated build system for our projects. That`s why I cannot give smallest project, that will fail, I want to discover how to debug your plugin. 

But could you give some clues how to discover actual typescript command, which compiled current buffer? How to modify this command to check which errors it produces?

**Comment by pyrho** [comment]
You can have a look at https://github.com/mhartington/nvim-typescript#debugging .
