### ISSUE TITLE
getCompletionData loop

### ISSUE THREAD

**Issue by deltaskelta** [mhartington/nvim-typescript#207]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

deoplete often doesn't show ts completions for multiple seconds, after investigating and watching the tsserver logs I see that while it is waiting for the completions to show there is some kind of loop on `getCompletionData` which looks like this.

```
Info 5979 [21:56:50.401] getCompletionsAtPosition: isCompletionListBlocker: 0                                                                           Info 5980 [21:56:50.462] getCompletionData: Semantic work: 61                                                                                           Info 5981 [21:56:50.463] getCompletionData: Get current token: 1                                                                                        Info 5982 [21:56:50.463] getCompletionData: Is inside comment: 0                                                                                        Info 5983 [21:56:50.463] getCompletionData: Get previous token 1: 0                                                                                     Info 5984 [21:56:50.463] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 5985 [21:56:50.519] getCompletionData: Semantic work: 56
Info 5986 [21:56:50.523] getCompletionData: Get current token: 0                                                                                        Info 5987 [21:56:50.523] getCompletionData: Is inside comment: 0
Info 5988 [21:56:50.523] getCompletionData: Get previous token 1: 0
Info 5989 [21:56:50.523] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 5990 [21:56:50.579] getCompletionData: Semantic work: 56
Info 5991 [21:56:50.580] getCompletionData: Get current token: 0
Info 5992 [21:56:50.580] getCompletionData: Is inside comment: 0
Info 5993 [21:56:50.580] getCompletionData: Get previous token 1: 0
Info 5994 [21:56:50.580] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 5995 [21:56:50.651] getCompletionData: Semantic work: 71
Info 5996 [21:56:50.653] getCompletionData: Get current token: 0
Info 5997 [21:56:50.653] getCompletionData: Is inside comment: 0
Info 5998 [21:56:50.653] getCompletionData: Get previous token 1: 0
Info 5999 [21:56:50.653] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 6000 [21:56:50.705] getCompletionData: Semantic work: 52
Info 6001 [21:56:50.705] getCompletionData: Get current token: 0
Info 6002 [21:56:50.706] getCompletionData: Is inside comment: 0
Info 6003 [21:56:50.706] getCompletionData: Get previous token 1: 0
Info 6004 [21:56:50.706] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 6005 [21:56:50.774] getCompletionData: Semantic work: 68
Info 6006 [21:56:50.777] getCompletionData: Get current token: 0
Info 6007 [21:56:50.777] getCompletionData: Is inside comment: 0
Info 6008 [21:56:50.777] getCompletionData: Get previous token 1: 0
Info 6009 [21:56:50.777] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 6010 [21:56:50.835] getCompletionData: Semantic work: 58                                                                                           Info 6011 [21:56:50.836] getCompletionData: Get current token: 0                                                                                        Info 6012 [21:56:50.836] getCompletionData: Is inside comment: 0                                                                                        Info 6013 [21:56:50.837] getCompletionData: Get previous token 1: 0                                                                                     Info 6014 [21:56:50.837] getCompletionsAtPosition: isCompletionListBlocker: 0                                                                           Info 6015 [21:56:50.909] getCompletionData: Semantic work: 72                                                                                           Info 6016 [21:56:50.910] getCompletionData: Get current token: 0                                                                                        Info 6017 [21:56:50.911] getCompletionData: Is inside comment: 0                                                                                        Info 6018 [21:56:50.911] getCompletionData: Get previous token 1: 0                                                                                     Info 6019 [21:56:50.911] getCompletionsAtPosition: isCompletionListBlocker: 0                                                                           Info 6020 [21:56:50.968] getCompletionData: Semantic work: 57                                                                                           Info 6021 [21:56:50.969] getCompletionData: Get current token: 0                                                                                        Info 6022 [21:56:50.969] getCompletionData: Is inside comment: 0                                                                                        Info 6023 [21:56:50.969] getCompletionData: Get previous token 1: 0                                                                                     Info 6024 [21:56:50.969] getCompletionsAtPosition: isCompletionListBlocker: 0                                                                           Info 6025 [21:56:51.27] getCompletionData: Semantic work: 58
Info 6026 [21:56:51.30] getCompletionData: Get current token: 0
Info 6027 [21:56:51.30] getCompletionData: Is inside comment: 0                                                                                         Info 6028 [21:56:51.31] getCompletionData: Get previous token 1: 1
Info 6029 [21:56:51.31] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 6030 [21:56:51.92] getCompletionData: Semantic work: 61
Info 6031 [21:56:51.93] getCompletionData: Get current token: 0
Info 6032 [21:56:51.93] getCompletionData: Is inside comment: 0
Info 6033 [21:56:51.93] getCompletionData: Get previous token 1: 0
Info 6034 [21:56:51.93] getCompletionsAtPosition: isCompletionListBlocker: 0
Info 6035 [21:56:51.148] getCompletionData: Semantic work: 55
Info 6036 [21:56:51.150] getCompletionData: Get current token: 0
Info 6037 [21:56:51.150] getCompletionData: Is inside comment: 0
Info 6038 [21:56:51.150] getCompletionData: Get previous token 1: 0
Info 6039 [21:56:51.150] getCompletionsAtPosition: isCompletionListBlocker: 0
```

It doesn't happen right away and only randomly happens in my workflow. Sometimes the loop goes on seemingly forever and I have to quit vim in order to reset the server.

## Environment Information

 * terminal: iterm2
 * vim/nvim version: nvim 0.3.1

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
scriptencoding utf-8
"let $NVIM_NODE_HOST_DEBUG=1
let g:python_host_prog = '/usr/local/bin/python2'
let g:python3_host_prog = '/Users/Jeff/bin/python'
let g:node_host_prog = '/usr/local/bin/neovim-node-host'
let g:ruby_host_prog = '/usr/local/bin/neovim-ruby-host'
let $NVIM_NODE_LOG_FILE='/tmp/nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='error'
let $NVIM_PYTHON_LOG_FILE='/tmp/nvim-python.log'
let $NVIM_PYTHON_LOG_LEVEL='info'

call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }


Plug 'HerringtonDarkholme/yats'
Plug 'mhartington/nvim-typescript', {'do': './install.sh', 'for': ['typescript', 'typescript.tsx']}

call plug#end()

let g:deoplete#enable_at_startup = 1

call deoplete#custom#option({
  \ 'smart_case': v:true,
  \ 'profile': v:true,
  \ })

call deoplete#custom#source(
  \ 'file', 'enable_buffer_path', v:false)

call deoplete#enable_logging('INFO', '/tmp/deoplete.log')
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#case_insensitive = 1

let g:deoplete#sources#ternjs#tern_bin = 'custom-tern' " for tern autocompleting
let g:tern#command = ['custom-tern'] " for running tern commands


```

## The reproduce ways from neovim starting

 1. open a file and poke around triggering completions until it happens

## Screen shot (if possible)

here is a video showing the tail of the tsserver logs and the htop reading for tsserver. If you watch the video until about 75% of the way through you will see it hit some completion data and then continued its loop. I have disabled all plugins and I am trying to track down the issue, but IDK where else to start looking

https://youtu.be/tiFPBxDtvz0

![screenshot 2019-01-02 22 13 39](https://user-images.githubusercontent.com/9424192/50593610-5a2cf300-0edc-11e9-91bc-b72d91875be6.png)

**Comment by deltaskelta** [comment]
I put some print statements in the deoplete python source and I started to see it being rapidly reprinted in the status bar when the error occurred.

It seems to be making repeated calls to the try loop here https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py#L34

![screenshot 2019-01-03 11 38 26](https://user-images.githubusercontent.com/9424192/50621904-85e7c180-0f4c-11e9-9a0b-76a0ba7a28a9.png)

**Comment by mhartington** [comment]
So this was done on purpose, but I think it might need to be revisited.

Essentially, we need to call `gather_candidates` multiple times to check to see if the completion res variable has been set to the correct values. 

```
    def gather_candidates(self, context):
        try:
            if context["is_async"]:
                res = self.vim.vars["nvim_typescript#completion_res"]
                if res:
                    context["is_async"] = False
                    self.vim.vars["nvim_typescript#completion_res"] = []
                    return res
            else:
                context["is_async"] = True
                [offset] = context["complete_position"] + 1,
                self.vim.vars["nvim_typescript#completion_res"] = []
                self.vim.funcs.TSDeoplete(context["complete_str"], offset)
            return []
        except:
            return []
```

**Comment by deltaskelta** [comment]
I might be onto something... It seems to maybe only get stuck in the loop when i trigger completions before the server fully starts. Ill have to test it out more tomorrow

**Comment by deltaskelta** [comment]
yeah I think this block needs to work differently. I have identified another problem with my print statements that happens when i type a `foo.` and it gets stuck trying to read the completion from the vim var forever without end.

I think my original problem happens when it gets stuck in an opposite loop where it hits the `else` block and continuously calls TSDeoplete although its hard to reproduce, that has to be what is happening. 

To fix this block I think we can either...

1. set a vim var with the server host and port info so we can make the request direct from python.
2. pass some messages between python and node using `gRPC` or `socket-io` or something so we can avoid using vim variables as a middle man

**Comment by mhartington** [comment]
🤔 

The server host/port is not a bad idea and could work. 

The second option seems pretty heavy handed IMO, but could serve an alternative.

**Comment by mhartington** [comment]
https://github.com/Microsoft/TypeScript/wiki/Standalone-Server-%28tsserver%29

So TSServer reads from stdin and writes to stdout. But since we control the process that tsserver starts in, we can make it anything.

**Comment by deltaskelta** [comment]
how would you do that? by wrapping it up into a node server that starts when the class is instantiated and just passing data to it?

I'm coming to realize that it might not even matter because the python method is still synchronous, so its a gamble on whether it will be more efficient bu we are still left with the choice of keeping basically the same code flow because we will still have to call the function, set context async, etc. which would be the same thing but more complicated. Right?

**Comment by deltaskelta** [comment]
I just realized, if everything is done from python, then that method could bypass all the `is_async` stuff and just be synchronous as long as it is still non-blocking on deoplete

**Comment by mhartington** [comment]
If a vim method is called, it's blocking though. I'll take a look at how the deoplete method can be better optimized.

**Comment by deltaskelta** [comment]
ok, I'm still trying to nail down what is causing this loop as it happens kind of rarely but I am getting closer. I'll update if I crack it

**Comment by deltaskelta** [comment]
So I think I have verified that nvim-typescript is not getting stuck in a loop because I haven't seen any messages in vim in over ten minutes and the TSServer is still running in circles and blocking any new responses. AFAIK I have run out of options that could be caused by this plugin so I have to open an issue on the Typescript repo

**Comment by deltaskelta** [comment]
FWIW, it looks like you can bind the tsserver to a socket https://github.com/Microsoft/TypeScript/blob/master/src/tsserver/server.ts#L918

**Comment by mhartington** [comment]
I think we can close this finally. Thanks for all the hard work @deltaskelta !
