### ISSUE TITLE
Unable to Select Items in Pop-Up

### ISSUE THREAD

**Issue by atomdmac** [mhartington/nvim-typescript#211]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
Unable to select suggestions from pop-up when used with `deoplete`.  When attempting to select items using the UP/DOWN arrow keys, items will appear to be selected for a split second, then become deselected again.  The pop-up will also "flicker" sometimes, making it look like it's constantly refreshing.

This happens specifically when `nvim-typescript` is installed and I'm using `nvim` to edit `*.ts` file.  `deoplete` works as expected once `nvim-typescript` is removed.

## Expected
Should be able to select suggestions.

## Environment Information

 * terminal: iTerm 3.2.6 (OSX)
 * vim/nvim version: 0.3.1

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin()
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting

 1. Open a TypeScript file
 2. Start typing a word that already appears in the current buffer
 3. When the auto-complete suggestions appear, attempt to select one of them with UP/DOWN arrow.
 4. Items will highlight for a brief moment before the pop-up will seem to "refresh" and deselect.

## Example project repo?

Most common errors are related to a project not being set up correctly.
Please provid a minimal project example to reduce back-and-forth time.
This makes debugging MUCH easier

## Screen shot (if possible)
![busted-ts](https://user-images.githubusercontent.com/1461736/51276065-aa5a8980-19a1-11e9-9757-23546d2f814c.gif)

**Comment by mhartington** [comment]
I've seen this as well, but not sure if this is do to the deoplete source being async, or other sources. Mine tends to happen when I have neco-look enabled.

**Comment by deltaskelta** [comment]
In the last day or two I have noticed this happen also. I haven't had time to investigate where it is coming from though as I have updated nvim and deoplete recently.

**Comment by Shougo** [comment]
I have reproduced the problem.

It is deoplete fault.
I will fix it later.  Please wait.

**Comment by Shougo** [comment]
I have fixed the problem completely.
Please use the latest version of deoplete.

**Comment by atomdmac** [comment]
@Shougo Looks to be working for me as well.  Thank you for the quick fix!

**Comment by mhartington** [comment]
Thanks @Shougo !
