### ISSUE TITLE
EDIT: TS3 Completion breaks TS2 projects

### ISSUE THREAD

**Issue by RodrigoLeiteF** [mhartington/nvim-typescript#212]
# Problems summary
No autocompletion happens at all.

## Expected
Vim suggests autocompletion.

## Environment Information

 * terminal: Terminator
 * vim/nvim version: v0.3.1

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')

Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
Plug 'Shougo/deoplete.nvim'
Plug 'Shougo/denite.nvim'
Plug 'ervandew/supertab'

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:SuperTabDefaultCompletionType = "<c-n>"
```

## The reproduce ways from neovim starting

1. Open file
2. Try to see auto completion for any variable

## Example project repo?
https://github.com/RodrigoLeiteF/brasilbot

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/16887983/51319306-d3cbf180-1a43-11e9-96db-85979fa2a956.png)

**Comment by deltaskelta** [comment]
did you update recently? If so can you run `:UpdateRemotePlugins` and restart vim?

**Comment by mhartington** [comment]
Looks like this is do to a TS3.x upgrade which introduced the `completionInfo` and removes `completions` request.

https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L13

We'll need to check the version and swap out the commands/args.

**Comment by mhartington** [comment]
A workaround for now though is to bump the typescript version to 3.x or higher @RodrigoLeiteF

**Comment by RodrigoLeiteF** [comment]
Awesome, that worked perfectly. Thank you :)

**Comment by mhartington** [comment]
Had some time, should be fixed!
