### ISSUE TITLE
2019 Goals

### ISSUE THREAD

**Issue by mhartington** [mhartington/nvim-typescript#214]
Hey folks! So this plugin has been my main "fun" side project for a bit. If you have used this plugin and you really like it! Awesome, I'm glad you like it. 

Anyways, it's easier for me to track some high level goals with them being written down.

- [ ] Clean up code base

Right now most of the logic is in a single index.ts file, which is slowly getting to around 900 LOCs.
Not that there's anything wrong with this, but it can for sure be more difficult to navigate and read.

I'd like to start splitting this up into more manageable modules that can be imported and reduce the noise in index.ts

- [ ] Improve developer experience

I've been looking around some other plugins to see how they behave and how the experience is with them. If possible, I'd like this plugin to provide a great developer experience. This is intentionally open to interpretation so I'll be looking for feedback 😄 . One feature in particular you can see below

![nvim-signature](https://user-images.githubusercontent.com/2835826/51748613-f9c44800-207a-11e9-9e40-fd0bafda0538.gif)

https://twitter.com/mhartington/status/1088788224485539840

- [ ] Close out remaining issue

Some issues have been hanging around for a bit. It's time to either address them or close them.

**Comment by pyrho** [comment]
Great initiative, thanks for all your work on this plugin @mhartington !

I am willing to help refactor the codebase, how would you like to proceed ? Maybe agree on a small high level architecture document/diagram of how it should be laid out?

If by "improving developer experience" you mean "us", I think having a document to help set up a debugging environment and a quick introduction on where to put a first breakpoint/console log would be helpful, the current README section is a bit lightweight :)

In any case, I'm here to help if you need.

**Comment by mhartington** [comment]
I think for code base cleanup... I like the approach VSCode has followed with things. 

https://github.com/Microsoft/vscode/tree/master/extensions/typescript-language-features/src

Where all the features are isolated, and then the top level command (in our case, the `@Commands` from nvim) can be thin wrappers that just call the function. I'm open to variations, but I think this is a good path to start on.

**Comment by deltaskelta** [comment]
A couple things I thought about when I was working on this plugin...

1. Can it be switched to use the functional style of nvim node? It seems like it would be easier to split up if it was that way

2. Add tests. I thought about adding some myself but I ran out of free time and I didn't have time to look into how to go about bringing up the whole nvim/TSServer environment for tests. I think the tests should include actual requests to the TSServer instead of mocking it since that is a huge part of the engine of this plugin

**Comment by pyrho** [comment]
+1 on unit/functional tests.

**Comment by mhartington** [comment]
> 1. Can it be switched to use the functional style of nvim node? It seems like it would be easier to split up if it was that way

I'm a little apprehensive about moving to the functional style. It seems cause a lot more confusion in just trying to find things. 

2. Test would be great! the core node-client has some good examples for testing features.

**Comment by williamboman** [comment]
Would using nvims new floating window support for stuff like `:TSType` make sense?

**Comment by mhartington** [comment]
Yes! This is on the road map and I have been following the pr to understand it. 

Mike Hartington

**Comment by Simmetopia** [comment]
I have experience writing tests with Jest, if you dont mind that as a dependency, i can write some unit tests

**Comment by mhartington** [comment]
@Simmetopia it's a devdep, so I dont mind

**Comment by williamboman** [comment]
Hey again :) Would it make sense to add support for renaming files (https://github.com/Microsoft/TypeScript/pull/23573) to nvim-typescript?
