### ISSUE TITLE
Option to remove semicolon from TSImport?

### ISSUE THREAD

**Issue by cj** [mhartington/nvim-typescript#216]
Is it currently possible to exclude the semicolon from `TSImport`?  If not, would this be considered as a future enhancement?

Cheers!

P.S. I noticed there is https://github.com/mhartington/nvim-typescript/blob/de424a7fce2248735f448b6051cc4094c8fd7d39/plugin/nvim_typescript.vim#L22 but it seems to have no effects on single imports i.e. `import React from 'react';`.

**Comment by mhartington** [comment]
👋 Hey there, sorry for the delayed response.

So this is bit of clean up I need to do. That option and the function it was used in is no longer needed. There's a built in method from typescript to handle adding any missing imports. It also creates the new text and import statements. It doesn't appear that there's an option to remove semi-colons, but something like prettier could be used instead.
