### ISSUE TITLE
[Question] Can :TSDef only support user definitions?

### ISSUE THREAD

**Issue by arnm** [mhartington/nvim-typescript#219]
Does :TSDef only work on user definitions? I am not able to go to definitions imported from other libraries.

I can go do `:TSDef` fine here:
```typescript
interface User {}

const u: User = {};
          ^----
```

But I can't do `:TSDef` on imported definition:

```typescript
import moment from 'moment';
       ^-----
```

Is this expected behavior? If so, any plans on adding this feature?

**Comment by deltaskelta** [comment]
TSdef works with imported definitions as well as user defined definitions. Make sure it is properly listed in your package.json and installed in the projects node modules. If you can re-create a reproduction of the issue with a minimal vimrc and an example project, please re-open this issue
