### ISSUE TITLE
Improve look of TSGetDiagnostics

### ISSUE THREAD

**Issue by aufula** [mhartington/nvim-typescript#221]
# Problems summary
TSGetDiagnostics show one line and cut the information off,  

## Expected
Better look and show full information

## Environment Information

 * terminal: mac terminal
 * vim/nvim version: 0.3.1

**Comment by mhartington** [comment]
Working on adding floating window support for this.

**Comment by mhartington** [comment]
Added supported for Floating Windows, should be good to go
![Screen Shot 2019-04-10 at 4 39 52 PM](https://user-images.githubusercontent.com/2835826/55911757-449c2900-5baf-11e9-8972-98fb004c18af.png)
