### ISSUE TITLE
TSComplete() does not work as omnifunc

### ISSUE THREAD

**Issue by Elemecca** [mhartington/nvim-typescript#222]
## Problem Summary

When `omnifunc` is set to `TSComplete` as recommended in #76, invoking omni completion via `<C-x><C-o>` prints this to the message window:

```plain
E745: Using a List as a Number
-- Omni completion (^O^N^P) Pattern not found
```

## Expected

The omni completion menu should open without errors.

## Environment Information

 * **terminal:** alacritty 0.2.9
 * **vim/nvim version:** nvim 0.3.4

## Minimal Configuration

HerringtonDarkholme/yats.vim@efaa6b5bce12f6700cf6a819dd80ddb881355f97 in `pack/syntax/start/yats`
nvim-typescript eca2bb92d45f in `pack/completion/start/nvim-typescript`

```vim
" init.vim
set omnifunc=TSComplete
```

## Reproduction Steps

1. `tsconfig.json`:
    ```json
    {}
    ```
1. `package.json`:
    ```json
    {
        "private": true,
        "devDependencies": {
            "typescript": "^3.3.3333"
        }
    }
    ```
1. `test.ts`:
    ```typescript
    interface Foo {
      bar?: string;
    }
  
    const foo: Foo = {};
    ```
1. npm/yarn install
1. open `test.ts` in nvim
1. add a line at EOF and type `foo.`
1. while still in insert mode, press `<C-x><C-o>`

**Comment by Elemecca** [comment]
This is happening because `TSComplete` only implements half of the contract for `omnifunc`. During completion `omnifunc` is called twice, first to find the start of the text to be completed, then again to get the actual completion results. See `:help complete-functions` for details. `TSComplete` doesn't check the value of `a:findstart`, so it returns the completion list from the first call, thus triggering the error.

This wrapper function works fine:
```vim
function TSOmniComplete(findstart, base)
  if a:findstart
    let line = getline('.')
    let start = col('.') - 1

    while start > 0 && line[start - 1] =~ '\k'
      let start -= 1
    endwhile

    return start
  else
    return TSComplete(a:base)
  endif
endfun

set omnifunc=TSOmniComplete
```

**Comment by mhartington** [comment]
Can you set omnifunc to be `TSOmnicFunc` instead? The issue you linked to was an older implementation that has sense changed. I need to add this to the docs

**Comment by Elemecca** [comment]
Ah, yes, that works. I'm not sure why I didn't see `TSOmnicFunc`; I was looking in that file.

**Comment by ms** [comment]
I can't seem to have access to `TSOmniFunc`. I see it in `rplugin/node/nvim_typescript/src/index.ts` but it's not showing up on auto complete of `:call TS<tab>` (`TSCloseWindow`, `TSEchoMessage` and `TSOnBufEnter` do) and vim complains if I set it as my omnifunc nonetheless.

Deoplete works, when enabled. I commented out everything related to deoplete though and ran `:PlugClean` and `:PlugInstall`. Am I missing something obvious?

**Comment by Elemecca** [comment]
@ms the function is, somewhat confusingly, called `TSOmnicFunc` (note the C), not `TSOmniFunc`.

**Comment by mhartington** [comment]
No ones perfect! Probably a spelling issue on my end. Will update and document.

**Comment by ms** [comment]
I can confirm `TSOmnicFunc` works! My bad for not reading the name properly. Thanks a lot

I'm surprised by the fact that `:UpdateRemotePlugins` doesn't somehow register all the functions for autocompletion?

For the documentation I recommend making it clear how to use the plugin without any dependency and separately indicate it meshes well with deoplete (and other plugins)

Thanks a ton for your work
