### ISSUE TITLE
TSOrganizeImports duplicates exports on last line

### ISSUE THREAD

**Issue by spejamchr** [mhartington/nvim-typescript#224]
# Problems summary

If a file ends in `export { foo, bar };` then `:TSOrganizeImports` duplicates that line.

```typescript
export { foo, bar };
export { foo, bar };
```

This doesn't happen if there are a couple blank lines after the export.

## Expected

Don't duplicate exports.

## Environment Information

 * terminal: Terminal.app
 * vim/nvim version: NVIM v0.3.4

## Minimal vim rc with less than 50 lines

```vim
" Use vim-plug
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.local/share/nvim/plugged')

" For Typescript support
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
call plug#end()
```

## Reproduce in neovim

 1. Create a `foo.ts` file with the contents:
```typescript
const foo = 1;
const bar = 2;

export { foo, bar };
```
2. Run `:TSOrganizeImports`

## Example project repo?

This doesn't require a project. Create a plain `foo.ts` file anywhere (I did it right in my home directory) with the contents above.

## Screen shot (if possible)

Before:

<img width="536" alt="Screenshot 2019-03-11 11 27 41" src="https://user-images.githubusercontent.com/7213059/54144142-bd616700-43f0-11e9-856f-8b4deba55c79.png">

After:

<img width="536" alt="Screenshot 2019-03-11 11 27 49" src="https://user-images.githubusercontent.com/7213059/54144146-bf2b2a80-43f0-11e9-988e-aa4b9a12d16d.png">

**Comment by mhartington** [comment]
Hi there! I'm not able to replicate this locally. I'm pushing some updates that could have fixed this.

**Comment by spejamchr** [comment]
I upgraded this plugin and then did `yarn global update neovim` and I don't see this issue anymore either. Maybe I was just using an old version of that package... Thank you for your help! :)
