### ISSUE TITLE
TSOmnicFunc reports "Unrecognized JSON command: completionInfo"

### ISSUE THREAD

**Issue by ajcrites** [mhartington/nvim-typescript#227]
# Problems summary
Trying to use `TSOmnicFunc` for omni completion does not work and reports "error processing"

```
TSOmnicFunc[1]...remote#define#request:

Unrecognized JSON command: completionInfo
```

## Expected
Omni completion should work with TSOmnicFunc

## Environment Information
 * terminal: zsh v5
 * vim/nvim version: nvim v0.3.4

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set runtimepath^=~/.config/nvim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state(expand('~/.config/nvim/dein'))
    call dein#begin(expand('~/.config/nvim/dein'))

    call dein#add('Shougo/dein.vim')
    call dein#add('HerringtonDarkholme/yats.vim')
    call dein#add('mhartington/nvim-typescript', {'build': './install.sh'})

    call dein#end()
    call dein#save_state()
endif

autocmd FileType typescript setl omnifunc=TSOmnicFunc
```

**Comment by mhartington** [comment]
Yeah, that looks like you're in a project with TS 2.x. As of TS3.x, the completion command has changed

https://github.com/mhartington/nvim-typescript/issues/212#issuecomment-455192857

Really, the completion function internally just needs to check the typescript version and send the correct command (on my todos, but been very busy recently)

**Comment by ajcrites** [comment]
Thanks, this helps. I'm a bit unclear on the workaround, though ... bump _which_  TypeScript version?

**Comment by mhartington** [comment]
Typically the typescript version in your project. IE `npm install typescript@latest --save-dev`

**Comment by ajcrites** [comment]
Ah I didn't realize that I was working on a project that was using TypeScript 2 🤦‍♂️. I switch around a lot. I can close this issue, or we can keep it open to track the change for TS 2 if you like.

**Comment by mhartington** [comment]
I'll close this for now and keep #212 around
