### ISSUE TITLE
Would it be possible to have :TSDef add to the tag stack?

### ISSUE THREAD

**Issue by ericfreese** [mhartington/nvim-typescript#228]
In other languages, I'm used to using `C-]` to go to the definition of a tag and then `C-t` to pop back to where I was. I can simulate it a bit with `nmap <C-]> :TSDef<CR>` and `C-o` to pop back, but I'm wondering if we could have better integration with the tag stack?

**Comment by mhartington** [comment]
So I've never actually used Tags in vim, so I'm not sure on how this should behave. Could you explain a bit more?

**Comment by ericfreese** [comment]
Sure, here's some more info:
- https://neovim.io/doc/user/tagsrch.html#CTRL-]
- https://neovim.io/doc/user/tagsrch.html#tagstack

I'm not the person to ask though on the more advanced features of tags or the implementation side since I only really use `C-]` and `C-t`.
