### ISSUE TITLE
Any easy way to add compile on save?

### ISSUE THREAD

**Issue by nastynaz** [mhartington/nvim-typescript#229]
# Problems summary
Currently this does not compile the source. Once I have edited files I need to manually run `tsc` to compile them. Is there any way to implement something like the `compileOnSave` option in `tsConfig.json` or have the client send a `CompileOnSaveEmitFileRequest` message?

As an aside: thanks for creating such a great plugin.

**Comment by mhartington** [comment]
I've thought about this before, and have considered it. Maybe do a build where it doesn't create any output? I'll see what I can do

**Comment by deltaskelta** [comment]
in most of my projects I add a command to the package.json file that runs `tsc --noEmit` which I use to check the whole project for errors. It would be cool if there was a command to run this and get project wide errors with an option to run it on save

**Comment by deltaskelta** [comment]
I think this is basically asking the same thing as #160

**Comment by mhartington** [comment]
Merging with #160
