### ISSUE TITLE
New error after updating, TSCloseWindow is unknown

### ISSUE THREAD

**Issue by Sammyalhashe** [mhartington/nvim-typescript#230]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
<img width="553" alt="Screen Shot 2019-04-22 at 3 30 55 PM" src="https://user-images.githubusercontent.com/20797997/56521872-ddb63280-6513-11e9-8da8-c5037d3714bd.png">
It appears after I updated the plugin to the most recent version I get this error (I'm using vim -plug so I use `:PlugUpdate`)

## Environment Information

 * terminal: iTerm2
 * vim/nvim version: NVIM v0.3.4

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin()

"Javascript Plugins
Plug 'pangloss/vim-javascript'
Plug 'ternjs/tern_for_vim', { 'do': 'npm install && npm install -g tern' }
Plug 'mxw/vim-jsx'
Plug 'Quramy/vim-js-pretty-template'
Plug 'MaxMEllon/vim-jsx-pretty'
Plug 'posva/vim-vue'
Plug 'Valloric/MatchTagAlways' " highlights matching html tags

"Typescript Plugins
"Plug 'leafgarland/typescript-vim'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}

call plug#end()

```

## The reproduce ways from neovim starting

 1. `nvim *.ts` (error shows)
 2. move cursor (error shows)

## Example project repo?

Just generally entering a typescript file

## Screen shot (if possible)
See above

**Comment by mhartington** [comment]
Have you run `UpdateRemotePlugins`?

**Comment by Sammyalhashe** [comment]
In which file should the function be normally?

**Comment by xaow** [comment]
Fixed this by going to nvim-typescript\rplugin\node\nvim_typescript, deleting node_modules, then running 'npm i' and 'npm run build'

**Comment by bastian-f** [comment]
The same is happening to me and the fix provided by xaow does not work. I followed the installation instructions. `UpdateRemotePlugins` gave an error, something about python, but I cannot reproduce it because `UpdateRemotePlugins` is not there as a command anymore.

**Comment by dragonofdeath** [comment]
Also noticed that issue happened with this commit https://github.com/mhartington/nvim-typescript/commit/2fd4da80cd31cd0314b437a9f68b6536ec67b2a2
Previous commit doesn't produce this error

**Comment by devth** [comment]
Same error for me on latest.

**Comment by mhartington** [comment]
Run `UpdateRemotePlugins`.

The commit mentioned by @dragonofdeath has _nothing_ to do with any functions.

**Comment by devth** [comment]
Tried that, still erroring.

<img width="874" alt="image" src="https://user-images.githubusercontent.com/86107/58335278-79caa680-7dfe-11e9-92f3-fada7c76d709.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/86107/58335306-8818c280-7dfe-11e9-8e47-dc8bf835a4e4.png">


<img width="718" alt="image" src="https://user-images.githubusercontent.com/86107/58335261-6c152100-7dfe-11e9-85f7-629c8b757e68.png">

**Comment by mhartington** [comment]
How are you building the src? 
Like when you update/build the plugin, you should be compiling things. 
Whats the minimal init.vim

A test case would be to cd into the plugin dir and running `install.sh`.
Otherwise, it's not clear what's happening.


Please open a **new** issue vs piling on an old closed issue.

**Comment by devth** [comment]
Sorry, looked relevant since it's the exact issue I'm having. Opening new issue.
