### ISSUE TITLE
[question] Possible to use in JS codebase?

### ISSUE THREAD

**Issue by fpereira1** [mhartington/nvim-typescript#231]
Hi, just a question
Is there a possibility to extend this plugin to work on a JavaScript codebase?
I'd like to use `:TsRefs` for example in a javascript project.  This is doable in vscode, so maybe it can be done here too?

**Comment by DonnieWest** [comment]
I use it all the time for JS codebases, notably some react stuff. That being said, I've had some problems with commonjs modules that I've not investigated yet

You do have to explicitly enable it for JS projects by setting `g:nvim_typescript#javascript_support`

**Comment by deltaskelta** [comment]
Yeah I was just going to say that the TSServer which is what this relies on supports JS so it should work as long as you activate this plugin for JS

**Comment by fpereira1** [comment]
That is excellent, thank you. I remember reading about this in the docs. It's working well
