### ISSUE TITLE
Unknown function TSCloseWindow

### ISSUE THREAD

**Issue by devth** [mhartington/nvim-typescript#233]
Continuation of https://github.com/mhartington/nvim-typescript/issues/230#issuecomment-495656060

```
  Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
```

After runnning `install.sh` (right) then moving cursor to a TSX file (left).

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/86107/58335737-7be13500-7dff-11e9-86dc-ef52ef11e51c.png">

**Comment by dragonofdeath** [comment]
For me  running ./install.sh and :UpdateRemotePlugins helped after all..

**Comment by devth** [comment]
Nuking everything and reinstalling fixes it. Is this required every time we update nvim-typescript?

**Comment by mhartington** [comment]
Shouldn't be. Not sure what was the issue on your end.

**Comment by marcobeierer** [comment]
I had the same issue, but running `./install.sh`, `:UpdateRemotePlugins` and reopening neovim fixed it... Not sure if `./install.sh` is necessary...

@mhartington Thanks for the great work!

**Comment by dman777** [comment]
I got this working in nvim by fixing python issues. But with normal Vim 8 I get this issue. Any ideas how to get rid of this issue in Vim 8?

**Comment by mhartington** [comment]
@dman777 This plugin does not support vim 8
