### ISSUE TITLE
error remote#define#AutoCmdOnHost

### ISSUE THREAD

**Issue by hristijankiko** [mhartington/nvim-typescript#238]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
I am trying to set up this plugin but after completing all the steps I get the following error message

```
hristijan@hristijan-linux:~/.cache/dein/repos/github.com$ nvim
Error detected while processing function remote#host#RegisterPlugin[31]..remote#define#AutocmdOnHost:
line   13:
E216: No such event: TextChangedP * call remote#define#AutocmdBootstrap("node", "/home/hristijan/.cache/dein/repos/github.com/mhartington/nvim-typescript/rplugin/node/nvim_typescript:autocmd:TextChangedP:*", v:false, "TextChangedP", {'group': 'RPC_DEFINE_AUTOCMD_GROUP_1', 'pattern': '*'}, "\"doau RPC_DEFINE_AUTOCMD_GROUP_1 TextChangedP \".fnameescape(expand(\"<amatch>\"))")
Press ENTER or type command to continue
```

Any idea what could be causing it?
I did install everything and did run :UpdateRemotePlugins

## Expected
The plugin to work correctly and not throw errors on nvim startup.

## Environment Information

 * terminal: ubuntu bash
 * vim/nvim version: nvim v0.2.2
python 2.7.15+
pip 9.0.1
node 8.10.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('HerringtonDarkholme/yats.vim')
  call dein#add('mhartington/nvim-typescript', {'build': './install.sh'})
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('Shougo/denite.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  call dein#end()
  call dein#save_state()
endif

let g:deoplete#enable_at_startup = 1
filetype plugin indent on
syntax enable
```

## The reproduce ways from neovim starting

 1. Happens on startup

## Example project repo?
Errors out on any file.

**Comment by mhartington** [comment]
This should be fixed in the latest release, as that hook was removed. But typically this happens if the plugin did not build and create the bindings.
