### ISSUE TITLE
Error message stays after fix

### ISSUE THREAD

**Issue by conradob** [mhartington/nvim-typescript#240]
# Problems summary
When there is an error related to a not found name, after fix, the error message stays in the buffer.

## Expected
After fix the error, the message should be cleared

## Environment Information

 * terminal: iterm 2
 * nvim version: NVIM v0.4.0-2348-g42bdccdf6

## Provide a minimal vim rc with less than 50 lines (Required!)
Running the default config for nvim-typescript, just enabling the deoplete
```vim
" Your minimal init.vim
let g:deoplete#enable_at_startup = 1
```

## Screen shot (if possible)
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1469697/61146855-e72bb700-a4d2-11e9-8deb-5995fd206819.gif)

**Comment by mhartington** [comment]
This should be fixed in the latest commits.
