### ISSUE TITLE
virtual text is cleared if diagnostics is enabled

### ISSUE THREAD

**Issue by musou1500** [mhartington/nvim-typescript#241]
# Problems summary

virtual text(annotation) on the buffer is cleared at regular intervals.
it occurs only if diagnostics is enabled.
it's will be a problem if use this plugin with other plugins that uses virtual text such as echodoc.vim 

I think diagnostics feature causes this problem.
`DiagnosticsProvider.clearHighlight` calls `nvim.buffer.clearNamespace`.
it clears virtual text.

please refer [official document](https://neovim.io/doc/user/api.html#nvim_buf_set_virtual_text()) for details
> Virtual text is cleared using |nvim_buf_clear_namespace|. 

## Expected
diagnostics should not clear virtual text.

## Environment Information

 * terminal: gnome-terminal 3.28.2
 * vim/nvim version: NVIM v0.3.7

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" I could not setup this plugin using `master` beanch.
" errors occured on my env(I'll create separated issue for it)
Plug 'mhartington/nvim-typescript', {
      \ 'do': './install.sh',
      \ 'commit': '1e976f105e92c5151654f493a5c590f310a8e728',
      \ }

" echodoc.vim (to show something on virtualtext)
Plug 'Shougo/echodoc.vim'

let g:echodoc#enable_at_startup=1
let g:echodoc#type="virtual"
" let g:nvim_typescript#diagnostics_enable = 1
```

## The reproduce ways from neovim starting

 1. install `nvim-typescript` and `echodoc.vim` (please see minimal vimrc)
 2. open any typescript file with neovim
 2. to show something on virtual text, use completion
 3. echodoc displays. but it's cleared soon.

## Screen shot (if possible)

![out](https://user-images.githubusercontent.com/5037195/61585514-cf6dc600-ab97-11e9-87f8-8853f69892b4.gif)

**Comment by mhartington** [comment]
Confirmed. Will fix. Thanks for the docs reference!
