### ISSUE TITLE
floating window does not closes when diagnostics is disabled

### ISSUE THREAD

**Issue by musou1500** [mhartington/nvim-typescript#243]
# Problems summary
floating window is closed by `TSCloseWindow` function when diagnostic is enabled.
but `TSCloseWindow` is not called when the diagnostic is disabled so the floating window is still displayed even if the cursor is moved.

## Expected

the floating window should be closed when cursor is moved even if diagnostic is disabled.

## Environment Information

 * terminal: gnome-terminal
 * vim/nvim version: NVIM v0.4.0-dev

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/nvim-typescript
let g:nvim_typescript#type_info_on_hold = 1
let g:nvim_typescript#diagnostics_enable = 0
```

## The reproduce ways from neovim starting

 1. hover symbol and display floating window
 2. move cursor

**Comment by musou1500** [comment]
for a workaround, I added following line to `ftplugin/typescript.vim`.

```vim
autocmd CursorMoved,CursorMovedI,InsertLeave *.ts call TSCloseWindow()
```

**Comment by mhartington** [comment]
You are correct! I'll fix this asap

**Comment by musou1500** [comment]
thank you.
