### ISSUE TITLE
ncm2 completion no longer working

### ISSUE THREAD

**Issue by mark-westerhof** [mhartington/nvim-typescript#245]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary

Recently updated this plugin which resulting in ncm2 completion to stop working. If i revert back to `1e976f105e92c5151654f493a5c590f310a8e728`, it's working again.

## Expected

ncm2 completion should work as before.

## Environment Information

 * terminal: alacritty
 * vim/nvim version: NVIM v0.3.8

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
...
Plug 'ncm2/ncm2-bufword'
Plug 'ncm2/ncm2-path'
Plug 'ncm2/ncm2-tern', {'do': 'npm install'}
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
...

"Typescript
let g:nvim_typescript#diagnostics_enable = 0
autocmd FileType typescript nnoremap <buffer> <C-]> :TSTypeDef<CR>
autocmd FileType typescript nnoremap <buffer> <Leader>] :TSDefPreview<CR>
autocmd FileType typescript nnoremap <buffer> <silent> K :TSDoc<CR>

"ncm2
autocmd BufEnter * call ncm2#enable_for_buffer()

set completeopt=noinsert,menuone,noselect
" set completeopt-=preview
autocmd CompleteDone * silent! pclose!

inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <expr><s-tab> pumvisible() ? "\<c-p>" : "\<tab>"

```

## The reproduce ways from neovim starting

 1. Open any typescript project, when completion should show (after entering period or import suggestion) no typescript suggestions are provided.

**Comment by mhartington** [comment]
Hmm, I just tested this out, and it seems to be working fine for me. The commit 1e976f105e92c5151654f493a5c590f310a8e728 didn't touch completion at all so I'm not sure what could be the issue.  Did you include `'roxma/nvim-yarp'` in your plugins?

**Comment by indeedhat** [comment]
i am getting the same issue on the latest commit, although it is not just auto complete with ncm2 that isnt working for me but also i get no errors or anything, as if there is no language server present.

I cant really give much in the way of useful information as i have just installed this plugin for the first time today but i can confirm that i have got 'roxma/nvim-yarp' installed

**Comment by mark-westerhof** [comment]
> Did you include 'roxma/nvim-yarp' in your plugins?

Yes, it's included.

I tried changing a few things in my vimrc to see if i could find something unique that i'm doing that's causing the issue, but no luck.

If it helps, you can see my full vimrc here: https://github.com/mark-westerhof/dotfiles/blob/75e094084e33046bb75985aa55c3c4fe2fd8c93a/vimrc

**Comment by nbardiuk** [comment]
For me it is not only completion, none of commands work.
Last commit when the plugin was working is https://github.com/mhartington/nvim-typescript/commit/1e976f105e92c5151654f493a5c590f310a8e728

On first broken revision https://github.com/mhartington/nvim-typescript/commit/eec19746858032eddf3630a307c1f9edf6b42d53 when I open typesript buffer I can see `Starting Server...` message but it never shows `Server started`. 
htop shows that `tsserver` is running.

    nvim  v0.3.8
    nodejs v10.16.0
    tst v3.4.3

**Comment by nbardiuk** [comment]
If I replace sign define call as it was before plugins works again

```ts
        await this.nvim.command(`sign define ${name} text=${data.signText} texthl=${data.signTexthl}`)
        // await this.nvim.call('sign_define', [name, { text: data.signText, texthl: data.signTexthl }]);
```

https://github.com/mhartington/nvim-typescript/blob/8af7f096a1f6813e00b6c544f2d99970203e0d30/rplugin/node/nvim_typescript/src/diagnostic.ts#L22-L23



There is a comment https://github.com/mhartington/nvim-typescript/commit/a5315f79802de93da6aa3e0aed0a1d8f5cfa0ef4#comments from @daliusd that `sign_define` is a new feature

**Comment by mhartington** [comment]
You need to update your version of nvim. I'm using newer API calls that are much more stable than older vim calls.

**Comment by nbardiuk** [comment]
Thanks for feedback. I hope you don't mind that I update required version in documentation and `:checkhealth`
