### ISSUE TITLE
TSGetDiagnostics window is appeared over TSType window

### ISSUE THREAD

**Issue by musou1500** [mhartington/nvim-typescript#248]
# Problems summary
TSGetDiagnostics window is appeared over TSType window if `type_info_on_hold` and `diagnostics_enable` is enabled.
it means that part of TSType window is hidden by TSGetDiagnostics.
please see the screenshot.

## Expected
I think to concat the content of these 2 floating windows is ideal.

```
|-------------------------------------------------------|
| let a: object                                         |
|-------------------------------------------------------|
| type '1' is not assignable to type 'object'.          |
|-------------------------------------------------------|
```

## Environment Information

terminal: gnome-terminal
vim/nvim version: NVIM v0.4.0-dev

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/nvim-typescript
let g:nvim_typescript#type_info_on_hold = 1
let g:nvim_typescript#diagnostics_enable = 1
```

## The reproduce ways from neovim starting

 1. create typescript file like following(includes a symbol that has type error)
 2. open it with neovim
 3. hover symbol that has type error

```typescript
let a: object = 1;
```

## Screen shot (if possible)

![Screenshot from 2019-08-01 02-31-17](https://user-images.githubusercontent.com/5037195/62234543-d7363180-b405-11e9-9d43-bee29e5cfa44.png)

**Comment by mhartington** [comment]
Something like this? 

https://youtu.be/xIK-8AItGCI

**Comment by musou1500** [comment]
Yes!
