### ISSUE TITLE
TSOnBufEnter runs on wrong buffer

### ISSUE THREAD

**Issue by RobWouters** [mhartington/nvim-typescript#250]
# Problems summary

When a *.ts file is open and a *.py file is opened using FZF in a split buffer, TSOnBufEnter gets run (supposedly because the *.ts file is still entered very briefly). When TSOnBufEnter fetches the current file it is the python file and the Typescript checks are run on the *.py file.

## Expected

Expect TSOnBufEnter to only run on the *.ts file.

## Environment Information

 * terminal: rxvt-unicode (urxvt) v9.21 - released: 2014-12-31
 * vim/nvim version: NVIM v0.4.0-dev

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/local/share/nvim/plugged')
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all'}
Plug 'junegunn/fzf.vim'
```

## The reproduce ways from neovim starting

 1. Open a *.ts file
 2. Search for a *.py file using :Files (FZF)
 3. Open *.py file with Ctrl-V, file gets opened in split buffer
 4. TSOnBufEnter is run on *.py file

## Example project repo?

Solution/workaround here:
https://github.com/RobWouters/nvim-typescript/commit/d8c09f68d3b7dd7992ded65e93762b501655bb03

## Screen shot (if possible)

![nvim-typescript-on-py-file](https://user-images.githubusercontent.com/345230/62923055-2e94b400-bdad-11e9-802a-729506bfff7f.png)

**Comment by RobWouters** [comment]
Thanks for looking into this!

However unfortunately this latest fix does not seem to fix the problem. I still get the exact same problem as described in the original issue.

I gather that the line "const file = await this.getCurrentFile()" already returns the wrong file.

I also found another, perhaps easier, way to demonstrate:
`vi typescript.ts +vs\ python.py`

**Comment by Peddle** [comment]
Hi +1 on this. Also encountering this issue

**Comment by lambdahands** [comment]
I'm also experiencing this bug. Could someone reopen the issue?
