### ISSUE TITLE
Error with TSOnBufLeave when not TS file 

### ISSUE THREAD

**Issue by conradob** [mhartington/nvim-typescript#251]
# Problems summary
When navigating to a non TS file it's showing an error:
```
Error detected while processing BufUnload Autocommands for "*.ts":
E117: Unknown function: TSOnBufLeave
```

## Environment Information

 * terminal: iterm 2
 * nvim version: NVIM v0.4.0-2348-g42bdccdf6

## Provide a minimal vim rc with less than 50 lines (Required!)
Running the default config for nvim-typescript, just enabling the deoplete
```vim
" Your minimal init.vim
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting
Moving through the files using buffers command `:b`
1 - Open the sample spec file `:e cypress/integration/sample.spec.ts`
2 - Open the fixture example file `:e cypress/fixtures/example.json`
3 - Switch between files with `b` command 
`:b cypress/integration/sample.spec.ts`
`:b cypress/fixtures/example.json`

## Example project repo?
https://github.com/omerose/cypress-support

## Screen shot (if possible)
![TSOnBufLeave-error](https://user-images.githubusercontent.com/1469697/63280407-a299f500-c2a2-11e9-8569-55beecb67d83.gif)

**Comment by mhartington** [comment]
Can you run `UpdateRemotePlugins`?

**Comment by conradob** [comment]
`:UpdateRemotePlugins` seems to solve the issue. I actually ran this soon after the plugin update and npm upgrade.

Thanks a lot for your support.
