### ISSUE TITLE
Find Local Typescript not showing for :checkhealth

### ISSUE THREAD

**Issue by kaihendry** [mhartington/nvim-typescript#252]
Carrying on from https://www.reddit.com/r/neovim/comments/cr0i7t/struggling_to_edit_type_script_like_vs_code/exezaqt/

Thanks ever so much for your help so far Mike.

I created https://github.com/kaihendry/archlinux-typescript-env to re-create my Archlinux environment.

https://s.natalian.org/2019-08-20/no-typescript.mp4

But now I don't have :TSdef at all. No **health#nvim_typescript#check** to be found!

**Comment by mhartington** [comment]
So following up on this, I think there's 2 things going on here...

1) There's a missing `call plug#end()` after the plugins. This will cause vim-plug to not load any plugins. 

2) *Maybe* some unused packages in the package.json caused the plugin build to fail, which is possible. But they have been removed as of ~10 mins ago 😬 


https://youtu.be/Spc026729RA

**Comment by kaihendry** [comment]
Nice catch.

I think https://github.com/kaihendry/archlinux-typescript-env is working for me now.
