### ISSUE TITLE
feature request: tooltips on hover (I mean, hovering with the cursor, not the mouse)

### ISSUE THREAD

**Issue by trusktr** [mhartington/nvim-typescript#262]
Would it be possible to show function information, etc, in tooltips? I'd like for them to appear automatically after a timeout, but also a command option similar to TSDoc but for opening a tooltip instead of a window would be nice. Is this possible?

**Comment by trusktr** [comment]
Ooooooh! Looks like this may be useful to use for the tooltips: https://github.com/neoclide/coc.nvim

**Comment by mhartington** [comment]
This should be possible already. 

https://github.com/mhartington/nvim-typescript/blob/master/doc/nvim-typescript.txt#L181

in the one-window branch, this already printing messages to floating windows.

![nvim-ts-#262](https://user-images.githubusercontent.com/2835826/69071430-e1e9f600-09f7-11ea-8b6b-07aaf6b76b37.gif)


Optionally, you could just call `TSType` instead.
