### ISSUE TITLE
TSRename resets unsaved buffer to saved states and breaks undo

### ISSUE THREAD

**Issue by ohcibi** [mhartington/nvim-typescript#265]
# Problems summary

When using `TSRename` in an unsaved buffer, the prompt correctly asks to rename the symbol under the cursor. It echos the right old name of that symbol even if the symbol does only exist in the unsaved buffer but not yet in the file on disk, i.e. up to this point `TSRename` parses the unsaved buffer and not the saved file.

However when it renames the symbol it uses the contents of the saved file instead of the unsaved buffer. It then replaces the contents of the unsaved buffer with the contents of the saved file with the renamed symbol.

## Expected

Renaming a symbol should be performed with the contents of the buffer and not the contents of the file on disk

## Environment Information

 * terminal: iTerm 3.3.7
 * vim/nvim version:
```
NVIM v0.5.0-b9c9283
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -W
no-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-c
olor=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191111-35126-2jdkt0/build/config -I/t
mp/neovim-20191111-35126-2jdkt0/src -I/usr/local/include -I/tmp/neovim-20191111-35126-2jdkt0/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xc
ode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191111-35126-2jdkt0/build/src/nvim/auto -I/tmp/neov
im-20191111-35126-2jdkt0/build/include
Compiled by ohcibi@korschenbroich.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-b9c9283/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal vim rc with less than 50 lines (Required!)

Inside a directory run `git clone https://github.com/mhartington/nvim-typescript` and use this `vimrc`:

```vim
" Your minimal init.vim
set runtimepath+=./nvim-typescript
```

## The reproduce ways from neovim starting

1. `nvim test.ts`
2. Insert `const foo;` **do not save!!** and put cursor on `foo`
3. `:TSRename`
4. Rename `foo` to something else
5. Quickfix list in fact reports correct replacement but buffer becomes empty
6. (in my real world project I cannot even undo this but in this minimal setup undoing the empty buffer works, so I'm just mentioning it because I don't know yet how to reproduce it. I will update the issue, if i find out)

**Comment by mhartington** [comment]
This should be fixed now.
