### ISSUE TITLE
Errors when editing a TS file after a few minutes

### ISSUE THREAD

**Issue by tsullivan** [mhartington/nvim-typescript#267]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
I have been using nvim-typescript for a few months. Recently it became unusable because I can only edit a file for about a few minutes before I start getting errors that block me from editing.
```
Error detected while processing function TSCloseWindow[1]..remote#define#notify:
line    6:
E475: Invalid argument: Channel doesn't exist
Press ENTER or type command to continue
```

## Expected
Typescript editing keeps working for as long as I need it to

## Environment Information
 * MacOS
 * terminal: iTerm2 3.3.7 / tmux 3.0a
 * vim/nvim version: NVIM v0.4.2

## Provide a minimal vim rc with less than 50 lines (Required!)
```vim
call plug#begin()
" JS / Typescript
if has('nvim')
  Plug 'autozimu/LanguageClient-neovim', { 'branch': 'next', 'do': 'bash install.sh' }
  Plug 'Shougo/vimproc.vim', { 'do': 'make' }
  Plug 'mhartington/nvim-typescript', { 'build': './install.sh' }
  " For async completion
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  " For Denite features
  Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' }
endif
Plug 'HerringtonDarkholme/yats.vim'
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting

 1. I'm not sure how to immediately reproduce the issue. It occurs after a few minutes of editing.

## Example project repo?
https://github.com/elastic/kibana

## Screen shot 
![image](https://user-images.githubusercontent.com/908371/72373653-f7ad2c00-36c5-11ea-88f4-f3cc3ac39e89.png)

When I run the `install.sh` script:
```
% ./install.sh
npm WARN neovim-test@1.0.0 No description
npm WARN neovim-test@1.0.0 No repository field.

audited 39 packages in 0.658s
found 0 vulnerabilities


> neovim-test@1.0.0 build /Users/tsullivan/.config/nvim/plugged/nvim-typescript/rplugin/node/nvim_typescript
> tsc --pretty -p tsconfig.json
```

When I run `UpdateRemotePlugins`:
```
:UpdateRemotePlugins
remote/host: node host registered plugins ['nvim_typescript']
remote/host: python3 host registered plugins ['denite', 'deoplete']
remote/host: generated rplugin manifest: /Users/tsullivan/.local/share/nvim/rplugin.vim

```

**Comment by tariqc80** [comment]
I also have been experiencing this error.  It seems to happen if I change buffers too fast, or if I leave vim open with a typescript file open for too long.  Doesn't always happen. but often enough.

**Comment by tariqc80** [comment]
Update:  I disabled the https://github.com/francoiscabrol/ranger.vim plugin, and it seems to be working now without issues, at least not as often.  The ranger plugin leverages `bclose`, which might actually be the issue with ranger, not ranger itself.  I'll spend more time troubleshooting later today.  Just wanted to share this preliminary observations, in case they help others.

FYI: I am able to trigger this behavior by speeding through buffers, e.g. going through errors in my quickfix list too fast.  This leads me to believe that the issue is buffer related.

**Comment by jeffvandyke** [comment]
I get a similar problem when using Ack.vim, it seems to be an issue when switching through multiple files at a speed somewhat faster than a snail's place. The only fix for me is to completely restart Neovim, which understandably leaves developer flow in a train-wreck. Even suppressing these errors, or allowing for tsserver restarts, would be better than the current state

**Comment by jeffvandyke** [comment]
Oh, and the kicker for this issue is that these errors show up with every move of the cursor and require Enter to dismiss, so it does completely break the editor when this happens.

**Comment by jeffvandyke** [comment]
Narrowed it down somewhat for me with a reliable reproduction. Fails with this init.vim file and [Ripgrep](https://github.com/BurntSushi/ripgrep) installed:
```
call plug#begin("~/.local/share/nvim/plugged")

Plug 'mileszs/ack.vim'
let g:ackprg = 'rg --vimgrep'

Plug 'mhartington/nvim-typescript', { 'do': './install.sh' }
" let g:nvim_typescript#type_info_on_hold = 1

augroup nvim_ts_bindings
  autocmd!
  autocmd FileType typescript call s:nvim_ts_setup()
  autocmd FileType typescriptreact call s:nvim_ts_setup()
  function! s:nvim_ts_setup() abort
    nnoremap K :TSType<CR>
    " lots of leader commands
    nnoremap <leader>ld :TSDef<CR>
    nnoremap <leader>lr :TSRename<CR>
    nnoremap <leader>lf :TSGetCodeFix<CR>
    nnoremap <leader>lt :TSTypeDef<CR>
    nnoremap <leader>lx :TSRefs<CR>
  endfunction
augroup end

" see deoplete's README.md
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_at_startup = 1
set completeopt=menuone,preview,longest,noselect

Plug 'sheerun/vim-polyglot'
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_flow = 1
let g:jsx_ext_required = 1 " Don't mix JSX in normal JS files, needed for Flow
au BufRead,BufNewFile,BufReadPost *.js.flow set filetype=javascript

call plug#end()
```

On Mac. I ran `rm -rf ~/.local/share/nvim`, re-installed <https://github.com/junegunn/vim-plug>, opened Neovim in a TypeScript project, ran `:PlugInstall`, ran `:UpdateRemotePlugins`, exited, run `nvim`, run `:Ack SomeTextInATsFile`, then:

Ack's find list opens up, along with a preview, and the statusline shows "nvim-ts: Starting Server...", and stays there forever.

As soon as I do anything to focus cursor into a typescript file, the following error happens:
```
Error detected while processing function TSOnBufEnter[1]..remote#define#notify:
line    6:
E475: Invalid argument: Channel doesn't exist
Press ENTER or type command to continue
```
... and the editor keeps throwing errors, including ones like:
```
Error detected while processing function TSCloseWindow[1]..remote#define#notify:
line    6:
E475: Invalid argument: Channel doesn't exist
Press ENTER or type command to continue
```

Hope that helps with reproduction, I'm not familiar enough with this plugin's code.

**Comment by atomdmac** [comment]
I'm seeing this as well.  I'm using `coc.nvim` rather than `deoplete` and I haven't applied any config customizations for `nvim-typescript`.

**Comment by atomdmac** [comment]
Update:  I tried adding this to my `init.vim` to see if I could get a more specific error message but the `nvim-node.log` file was empty after recreating the error:
```
let $NVIM_NODE_LOG_FILE='nvim-node.log'
let $NVIM_NODE_LOG_LEVEL='warn'
```

**Comment by atomdmac** [comment]
This seems likely to be either the same cause or related to what we're seeing here: https://github.com/neovim/neovim/issues/4468

**Comment by gabrielhpugliese** [comment]
I have this error in Fev. 2021 - installed the plugin yesterday. You guys had it fixed somehow?

**Comment by atomdmac** [comment]
@gabrielhpugliese I was never able to find a solution so I had to stop using this plug-in unfortunately.  I've been able to replace of the functionality with the `Quramy/tsuquyomi` plug-in, though.

**Comment by Qix-** [comment]
Yeah this plugin is broken and doesn't seem to be maintained anymore, unfortunately. Thanks for the rec @atomdmac, I'll give it a try.

**Comment by atomdmac** [comment]
I've since switched to using `vim-lsp` and `vim-lsp-settings` which I have also had pretty decent success with.  I've been using this setup for my daily work for about a month and I really like it.

**Comment by Shougo** [comment]
You should read this.

https://github.com/mhartington/nvim-typescript#deprecated

**Comment by tsullivan** [comment]
> https://github.com/mhartington/nvim-typescript/issues/267#issuecomment-877545685

Same here. Closing this issue
