### ISSUE TITLE
TSDef is doing nothing or fails silently.

### ISSUE THREAD

**Issue by danbruegge** [mhartington/nvim-typescript#269]
**Warning:  I will close the issue without the minimal vimrc and the reproduce ways.**

# Problems summary
Call `TSDef` will not jump to definition of the method/variable. 

`TSDefPreview` or `TSDoc` for example are working fine.

ALE's `ALEGoToDefinition` for example, is working fine.

## Expected
Call `TSDef` will jump to definition of the method/variable.

## Environment Information

 * terminal: `termite v15-1-g7e9a93b` + `tmux 3.0a`
 * vim/nvim version:
```
$ nvim --version
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/bundle')
Plug 'mhartington/nvim-typescript', {'do': './install.sh'}
call plug#end()

let g:nvim_typescript#javascript_support = 1
let g:nvim_typescript#diagnostics_enable = 0

nmap <silent> gd :TSDef<CR>
nmap <silent> gr :TSRefs<CR>
nmap <silent> gi :TSType<CR>
```

## The reproduce ways from neovim starting

 1. start neovim with typescript file
 2. position cursor under function you want the definition
 3. call `:TSDef`

**Comment by pgebheim** [comment]
I'm getting the same behavior, for what it's worth. Haven't yet found a solution.

**Comment by danbruegge** [comment]
My workaround for now is replacing TSDef with ALEGoToDefinition for my shortcut: `nmap <silent> gd :ALEGoToDefinition<CR>`

**Comment by reissbaker** [comment]
It looks like this was introduced in #260; if you check out the commit right before that one (10a93d8ebd8524418479c4e4814d45ddc5d360ef) and run `install.sh`, `:TSDef` starts working again.

**Comment by reissbaker** [comment]
It's because #260 updated the `typescript` package to 3.6, which changed the shape of `DefinitionResponse`: it now uses [`FileSpanWithContext`](https://github.com/microsoft/TypeScript/blob/master/lib/protocol.d.ts#L646) rather than [`FileSpan`](https://github.com/microsoft/TypeScript/blob/release-3.4/lib/protocol.d.ts#L658), meaning the response uses `contextStart` and `contextEnd` rather than `start` and `end` as keys.

FWIW, I believe the TypeScript compiler would catch these kinds of errors if the `tsconfig` set `strict` to `true`.

**Comment by reissbaker** [comment]
Actually, it seems like it was just a stray `console.warn` that was causing the failure. Not sure why that would break anything, but I opened a PR with a fix that makes `:TSDef` work for me again.

**Comment by mhartington** [comment]
Just merged that in. Thanks @reissbaker !
