### ISSUE TITLE
Stuck floating windows

### ISSUE THREAD

**Issue by sassanh** [mhartington/nvim-typescript#277]
Unfortunately I wasn't able to reproduce it reliably

# Problems summary
Floating windows sometimes don't close and stay there forever

## Environment Information

 * terminal: iTerm
 * vim/nvim version: v0.5.0-nightly-109-g08efa7037 (and many other versions of neovim including stable 0.5)

## Provide a minimal vim rc with less than 50 lines (Required!)

Unfortunately I wasn't able to reproduce it reliably

## The reproduce ways from neovim starting

 1. Play around a typescript file

## Example project repo?

Unfortunately I wasn't able to reproduce it reliably, it happens in two of my projects and `nvim-typescript` codebase itself

## Screen shot (if possible)

<img width="1132" alt="image" src="https://user-images.githubusercontent.com/1270688/88509211-d5da1d80-cff5-11ea-83a0-0adf7e287353.png">

I think the current codebase has some issues regarding asynchronous stuff, for example I think currently it is possible that `createFloatingWindow` is called two times simultaneously because we don't have a locking mechanism, so I tried to solve it by doing something like this in `one-window` branch, but no luck so far: (it indeed avoids multiple windows, but sometimes it goes into an state that no window is shown at all)

```diff
diff --git a/rplugin/node/nvim_typescript/src/index.ts b/rplugin/node/nvim_typescript/src/index.ts
index 3b31451..4e87374 100644
--- a/rplugin/node/nvim_typescript/src/index.ts
+++ b/rplugin/node/nvim_typescript/src/index.ts
@@ -25,16 +25,44 @@ export default class TSHost {
   doingCompletion = false;
   suggestionsEnabled: any;
   updateTime: number;
+  windowLock = false;
+
   constructor(public nvim: Neovim) { }
 
 
   @Autocmd('CompleteDone', { pattern: '*' })
   async onCompleteDone() {
-    console.warn("COMPLECTION DONE")
     this.doingCompletion = false
     this.getDiagnostics()
   }
 
+  async showInWindow(symbol: any, type: "Error" | "Type"): Promise<void> {
+    if (this.windowLock) {
+      await new Promise((resolve) => {
+        const intervalId = setInterval(() => {
+          if (!this.windowLock) {
+            clearInterval(intervalId);
+            resolve();
+          }
+        }, 100);
+      });
+    }
+    this.windowLock = true;
+    try {
+      if (!this.floatingWindow) {
+        this.floatingWindow = await createFloatingWindow(this.nvim, symbol, 'Type')
+      } else {
+        this.floatingWindow = await updateFloatingWindow(this.nvim, this.floatingWindow, symbol, 'Type');
+      }
+    }
+    catch {
+      // Probably window was closed by the user
+      this.floatingWindow = null;
+      await this.showInWindow(symbol, type);
+    }
+    this.windowLock = false;
+  }
+
   @Command('TSType')
   async getType() {
     await this.reloadFile();
@@ -43,14 +71,9 @@ export default class TSHost {
       const typeInfo = await this.client.quickInfo(args);
       if (Object.getOwnPropertyNames(typeInfo).length > 0) {
         try {
-          if (!this.floatingWindow) {
-            this.floatingWindow = await createFloatingWindow(this.nvim, typeInfo, 'Type')
-          } else {
-            this.floatingWindow = await updateFloatingWindow(this.nvim, this.floatingWindow, typeInfo, 'Type');
-          }
+          this.showInWindow(typeInfo, 'Type');
         }
         catch (e) {
-          console.warn("ERROR", e)
           await printHighlight(this.nvim, await truncateMsg(this.nvim, typeInfo.displayString), 'MoreMsg', 'Function');
         }
       }
@@ -534,12 +552,7 @@ export default class TSHost {
     if (errorSign) {
       (debounce(async () => {
         try {
-          if (!this.floatingWindow) {
-            this.floatingWindow = await createFloatingWindow(this.nvim, errorSign, 'Error')
-
-          } else {
-            this.floatingWindow = await updateFloatingWindow(this.nvim, this.floatingWindow, errorSign, 'Error')
-          }
+          this.showInWindow(errorSign, 'Error');
         }
         catch (e) {
           await printHighlight(this.nvim, await truncateMsg(this.nvim, errorSign.text), 'ErrorMsg');
```

**Comment by gunar** [comment]
Same here.

Wondering if it has anything to do with [vim-auto-save](https://github.com/907th/vim-auto-save). @sassanh do you happen to have that plugin installed as well?

**Comment by sassanh** [comment]
No I don't have that plugin.
This issue was so annoying that unfortunately I ended up using coc.nvim against my will (I didn't like coc.nvim running a js package manager in parallel with my vim-plug package manager.)

**Comment by mhartington** [comment]
I just pushed a fix based on the suggestions from @sassanh (good stuff).

I'm honestly winding down nvim-typescript in favor of using nvim built in LSP. 
It's the future of neovim and really just makes my plugin (and coc for that matter) obsolete
