### ISSUE TITLE
Error Invoking TSOmniFunc: No content available

### ISSUE THREAD

**Issue by oncomouse** [mhartington/nvim-typescript#279]
# Problems summary

I'm trying to use this plugin with [vim-mucomplete](https://github.com/lifepillar/vim-mucomplete), which uses the omnifunc to generate a completion menu. When autocompletion triggers while I'm defining a new variable or function, I get the following error:

~~~
Error detected while processing function TSOmniFunc[1]..remote#define#request:               
line    2:
Error invoking '/Users/apilsch/.vim/plugged/desktop/nvim-typescript/rplugin/node/nvim_typescript:function:TSOmniFunc' on channel 5:
No content available.
~~~

This error is also produced when I manually trigger the omnifunc (via `<C-X><C-O>`) while declaring a new variable. I've attached an animated GIF of the error, in case my explanation of what's happening isn't clear.

## Environment Information

 * terminal: kitty
 * vim/nvim version: neovim 0.44
* typescript: 4.0.3

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
filetype plugin on
set runtimepath+=~/.vim/plugged/desktop/nvim-typescript
let g:nvim_typescript#javascript_support = 1
augroup ts
  autocmd!
  autocmd FileType javascript setlocal omnifunc=TSOmniFunc
augroup END
```

## The reproduce ways from neovim starting

1. `:set omnifunc=TSOmniFunc`
1. `i`
1. `var tes`
1. `<C-X><C-O>`

## Screen shot (if possible)

![nvim](https://user-images.githubusercontent.com/2666761/95907269-df576400-0d60-11eb-8a80-7d67b6a823dd.gif)

**Comment by mhartington** [comment]
Should be fixed now! Just update your plugin
