### ISSUE TITLE
Deprecate yats as official syntax in favor of NeoVim's

### ISSUE THREAD

**Issue by gunar** [mhartington/nvim-typescript#281]
I'd like to propose we start treating NeoVim's native syntax file as the official one for `nvim-typescript` instead of `yats.vim`. This would mean making sure it's currently compatible, guaranteeing compatibility moving forward, and removing the suggestion to add `yats` from the README.

What do you think?

PS: `nvim-typescript` is awesome, thank you so much for your work

**Comment by drybalka** [comment]
Actually for me the native file does not work - for some reason nvim-typescript does not see it. However, if I install yats everything seems to be working fine. Am I missing something?

**Comment by gunar** [comment]
For anyone watching this issue, it's been closed because the repo has been deprecated in favor of NeoVim's native ~syntax files~ LSP (EDIT/FIX).

**Comment by mhartington** [comment]
It's been closed because of neovim native LSP.

**Comment by gunar** [comment]
If anyone else is as lost as I am in migrating to the native LSP, this might help you: https://neovim.io/doc/user/lsp.html
