### ISSUE TITLE
Not an editor command: TSStop

### ISSUE THREAD

**Issue by yogeshlonkar** [mhartington/nvim-typescript#284]
# Problems summary
Error when existing vim after editing non TypeScript file. Below is error
```log
Error detected while processing VimLeavePre Autocommands for "*":
E492: Not an editor command: TSStop
```

## Expected
No errors to be shown

## Environment Information

 * terminal: iterm2
 * vim/nvim version:
<img width="672" alt="image" src="https://user-images.githubusercontent.com/10169201/124960324-7dd8d300-e01c-11eb-9f2a-9da58d6b7686.png">

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
set shell=/usr/bin/env\ zsh

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'mhartington/nvim-typescript', {'for': ['typescript', 'tsx'], 'do': './install.sh' }
call vundle#end()

filetype plugin indent on
syntax on
```

## The reproduce ways from neovim starting

 1. Open any file expect TypeScript
 2. Perform changes in file
 3. `set verbosefile=error.log` to capture error message at the exit
 4. Exist vim

## Work around
Editing [nvim_typescript.vim#L190](https://github.com/mhartington/nvim-typescript/blob/44f3db3331632003ed95d963b0753ef94abc8b90/plugin/nvim_typescript.vim#L190)
```diff
-  autocmd VimLeavePre * TSStop
+  autocmd VimLeavePre * if exists(":TSStop") | exe ":TSStop" | endif
```

**Comment by mhartington** [comment]
You likely did not run `UpdateRemotePlugins`. Please see the plugin readme


>If errors occur after installing, make sure to run ./install.sh in the plugin directory. And try to run :UpdateRemotePlugins if you haven't already.


Also worth noting I deprecated this plugin in favor of nvim 0.5's built in lsp. Use that.
