### ISSUE TITLE
Javascript support

### ISSUE THREAD

**Issue by DonnieWest** [mhartington/nvim-typescript#32]
I noticed this was removed: what is specifically holding us back? How can we make this more ideal?

**Comment by mhartington** [comment]
Needs some tweaking to work with how now server is started.

I had it working "kinda" locally, but it just needed clean up and more thought.

Also, I want to tackle #30 before more features are added.

**Comment by DonnieWest** [comment]
@mhartington would you be open to a PR for javascript support now that #30 is closed? If so, you mentioned that you had it kinda working locally, would you mind sharing any roadblocks you faced that I should keep in mind?

**Comment by mhartington** [comment]
so the main issue that I had was actually returning data. 
Seems that if the user does not have a jsconfig.json, tsserver wont return any values. 
This may be fixed via typescript, but I haven't looked too much yet.

**Comment by DonnieWest** [comment]
Hmm, my original plan was to just assume that the user has a valid jsconfig.json. I'm looking around and it seems like we can set the default compiler options [based on this from the protocols file](https://github.com/Microsoft/TypeScript/blob/master/lib/protocol.d.ts#L47)

I'm thinking that would be best done in two PRs. One for rudimentary Javascript support provided a proper jsconfig.json and another setting up default compiler options for inferred projects. What do you think?

**Comment by mhartington** [comment]
Right now, if neither jsConfig or tsconfig are present I jsut return nothing, so I think this will work fine.

Yes, I think 2 prs will work.
I just added back the variable for js support, defaulting to `g:nvim_typescript#` for the namespace.

**Comment by DonnieWest** [comment]
This is now in master, so, closing this :)

**Comment by mhartington** [comment]
@DonnieWest just removed this again. 
There were to many issues trying to get it to work and it ended up being very slow.

I think if people want JS support, they can user tern instead. As that is what the tool is built for.

**Comment by DonnieWest** [comment]
@mhartington I've been fiddling with this locally since some of those issues were revealed. It seems like we're doing too much work in the __init__ file. Removing the unused variables being initialized seems to fix the issue for me locally. Specifically here fixed it for me https://github.com/mhartington/nvim-typescript/blob/02c1e33c43511a0b5239f436187f55ee385e98a9/rplugin/python3/nvim-typescript/__init__.py#L71-L72

Do you have any other examples of this being slow? I use this pretty actively for it's Javascript support and would love to continue to do so.

**Comment by DonnieWest** [comment]
Not to continue bothering you on a closed issue, but, thank you! Your work is amazing and this is an awesome tool :)
