### ISSUE TITLE
Realtime (as you type) error reporing

### ISSUE THREAD

**Issue by whitecolor** [mhartington/nvim-typescript#37]
Like it is done in VSCode:
![image](https://cloud.githubusercontent.com/assets/736697/22060410/70fa4f9c-dd92-11e6-8386-e7b55ba88c01.png)

I believe it should be done using the same TSServer running by `nvm-typescript` not by some syntax or linter checkers, as errors should be shown as you type, not as you save.

**Comment by mhartington** [comment]
This can be configured through 
https://github.com/neomake/neomake/

**Comment by whitecolor** [comment]
How can it be configured to show errors "as you type"? I'm not sure, [but it seem to be not solved](https://github.com/neomake/neomake/issues/543). And each time you run `tsc` for file it takes at least a few seconds on a medium size project. When you working with  TSServer you get immediate feedback, VSCode acts this way as I believe tsuquyomi does as well.

**Comment by mhartington** [comment]
Tsuguyomi does not behave this way at all. 
They integrate with syntastic, but still require syntastic to be called and run when ever.

VSCode does do this, but can be super slow and gets bogged down because it's constantly running. 


Again, I'm not building a linting engine, that is neomakes job.

**Comment by whitecolor** [comment]
Well it is not about linting (which helps to keep codestyle and keep from potentially unhealthy constructs) but about showing compilation errors before they actually occur.

> VSCode does do this, but can be super slow and gets bogged down because it's constantly running.

Well, sometimes it really gets stacked. But very rarely, I think it will be improved in future. Do you think it is not the valid approach?

**Comment by mhartington** [comment]
Feel free to make a PR.


For me, its fine letting neomake handle things.
