### ISSUE TITLE
Error while trying to use local dev version

### ISSUE THREAD

**Issue by whitecolor** [mhartington/nvim-typescript#38]
Wanted to setup for local dev:

Cloned `nvm-typescirpt` to `/mnt/d/Code/nvim-typescript`

added local plugin config:
```vim
  call dein#local('/mnt/d/Code', {}, ['nvim-typescript'])
```
and params:
```vim
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_ignore_case = 1
  let g:deoplete#auto_complete_start_length = 1
  let g:auto_complete_start_length = 1
  let g:deoplete#enable_refresh_always = 1
  let g:deoplete#enable_debug = 1
  let g:deoplete#enable_profile = 1
  call deoplete#enable_logging('DEBUG', '/deoplete.log')
 
```

And got such erros in the neovim:

![image](https://cloud.githubusercontent.com/assets/736697/22114943/f2547a0e-de8c-11e6-89f8-3226a3e5f1c5.png)

Any ideas?

**Comment by mhartington** [comment]
The server never started.
This happens when you're trying to either run with a ts syntax file 

>if no completion is happening, please be sure to have a Typescript syntax file in your RTP. Neovim does not include a default syntax for Typescript, so be sure to include one. A popular syntax file for Typescript is yats.vim


Or since the start of the client is handled by the remote plugin, you never ran `UpdateRemotePlugins`

**Comment by whitecolor** [comment]
Ok. Yes After `UpdateRemotePlugins` it launches but it doesn't seem to use updated code, I updated `TS: Server Started` string in `__init__.py` and still see the same string in the log. When you update the code, how do you relaunch nvim to test code updates?

**Comment by mhartington** [comment]
do you have the plugin already loaded from github?

**Comment by whitecolor** [comment]
Yes it is cloned to `/mnt/d/Code/nvim-typescript`

**Comment by mhartington** [comment]
no, I mean, do you have a remote copy, and a local copy being loaded?


```
  call dein#add('mhartington/nvim-typescript')
  call dein#local('/mnt/d/Code', {}, ['nvim-typescript'])
```

**Comment by whitecolor** [comment]
No, I commented it out from config, I also checked that there is no remote version in `/dein.vim/repos/github.com/mhartington/nvim-typescript` 

I too have filling that it uses original remote version, but I can not get how.

**Comment by mhartington** [comment]
I dont have time right now, as I am working.

But call `: call dein#recache_runtimepath()` and `UpdateRemotePlugin` again

**Comment by whitecolor** [comment]
No effect, I already removed deplete.vim and installed again

**Comment by whitecolor** [comment]
Ok, it seem to work now. Thanks, closing.

**Comment by whitecolor** [comment]
Actually, it seems that the problem was just that `__init__.py` has two places with `TS Server Started` messages. And I modified only one. ha.
