### ISSUE TITLE
E117: Unknown function: NvimTSEnter

### ISSUE THREAD

**Issue by mastertinner** [mhartington/nvim-typescript#43]
When I open a `.ts` file with vim, I get the following errors:

```txt
Error detected while processing BufEnter Auto commands for "*.ts":
E117: Unknown function: NvimTSEnter
```

Autocompletion with deoplete doesn't work. It works in other file types (e.g. JavaScript files).

I'm using NeoVim `0.1.7` and have `tsc` `2.1.6` globally installed. My dotfiles with all installed plugins and `.vimrc` can be found here: https://github.com/mastertinner/dotfiles/tree/master/vim

I'm not sure if it's a problem that I'm using `leafgarland/typescript-vim` as a TypeScript syntax file.

**Comment by mhartington** [comment]
can you pull the latest and run `UpdateRemotePlugins`

**Comment by mastertinner** [comment]
You are amazingly fast! That fixed it. Thanks a lot for the quick fix, @mhartington!

**Comment by jacob-israel-turner** [comment]
@mhartington I'm getting this same error today.  😬

**Comment by undu** [comment]
I'm having the same issue, `:UpdateRemotePlugins` doesn't fix it.

I double-checked typescript was installed globally, and for some reason when it gives this errors it also marks some line as having errors, with complete error messages. This happens a couple of times per linter run. (the error appears twice)

I'll check in a few hours in another machine to see if it's related to this machine config.

**Comment by mhartington** [comment]
Please provide more info.
How can I replicate?
Minimal vimrc?
Have you run `UpdateRemotePlugins`

Please open a new issue and do not re-post on older ones.
