### ISSUE TITLE
deoplete crashes in gather_results

### ISSUE THREAD

**Issue by Kasama** [mhartington/nvim-typescript#47]
# Problems summary

Whenever completion starts deoplete crashes saying it coulndn't get completions from: typescript.

I have seen issue #46, although similar errors appear, I have the [tsconfig.json](https://github.com/driftyco/ionic2-app-base/blob/master/tsconfig.json) file in `:pwd` directory

## Expected

Completion options should show up in vim's completion candidates box
## Environment Information

 * OS: Arch Linux running Linux 4.9.17-1-lts
 * terminal: Terminator running ZSH inside TMUX session
 * vim/nvim version: NVIM v0.1.7
 * python3: 3.6.0
 * `pip3 freeze | grep neovim`: neovim==0.1.13
 * `:CheckHealth`: [Here](http://pastebin.com/cMr1XMSn)

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
syntax on

"" Init Plug
let plugged_path=expand('~/myMinimalConfig/plugged')
call plug#begin(plugged_path)

Plug 'mhartington/nvim-typescript'
  Plug 'Shougo/deoplete.nvim'
  Plug 'HerringtonDarkholme/yats.vim'

call plug#end()
filetype plugin indent on
" Plug Done

" deoplete config {
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_debug = 1
  let g:deoplete#enable_profile = 1
  let g:deoplete#enable_ignore_case = 1
  call deoplete#enable_logging('DEBUG', '/tmp/deoplete/deoplete.log')
" }

```
(vimrc assuming [Plug](https://github.com/junegunn/vim-plug) to be installed and `:PlugInstall` already ran)

## The reproduce ways from neovim starting

 1. `cd` to base ionic app root (directory that has `tsconfig.json` in it)
 2. open nvim `nvim -u ~/myMinimalConfig/vimrc test.ts`
 3. update remote plugins (`:UpdateRemotePlugins`)
 4. paste simple class
```typescript
class Animal {}
```
 5. type `o` to enter insert mode on next line
 6. type `An` and wait for automatic completion to kick in
 7. Screenshot 1 shows up
 8. `ESC` to exit insert mode
 9. `:message`
 10. Screenshot 2 shows up

## Example project repo?
[base ionic app](https://github.com/driftyco/ionic2-app-base)
installed using `ionic start test --v2`

### Screenshot 1

![2017-03-25-183723_1366x768_scrot](https://cloud.githubusercontent.com/assets/1714520/24326298/3b0a64a4-118a-11e7-8f69-8518ce868a7a.png)

### Screenshot 2

![2017-03-25-184005_1366x768_scrot](https://cloud.githubusercontent.com/assets/1714520/24326319/821c1626-118a-11e7-971f-2e49ccc631e0.png)

Text:
```
[deoplete] Logging to /tmp/deoplete/deoplete.log
TS: Server Started
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/roberto/testNvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 124, in gather_results
[deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
[deoplete]   File "/home/roberto/testNvim/plugged/nvim-typescript/rplugin/python3/deoplete/sources/typescript.py", line 84, in gather_ca
ndidates
[deoplete]     self.reload()
[deoplete]   File "/home/roberto/testNvim/plugged/nvim-typescript/rplugin/python3/deoplete/sources/typescript.py", line 58, in reload
[deoplete]     self._client.reload(filename, tmpfile.name)
[deoplete]   File "/home/roberto/testNvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/client.py", line 186, in reload
[deoplete]     response = self.send_request("reload", args, True)
[deoplete]   File "/home/roberto/testNvim/plugged/nvim-typescript/rplugin/python3/nvim-typescript/client.py", line 134, in send_request
[deoplete]     ret = json.loads(returned_string)
[deoplete]   File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
[deoplete]     return _default_decoder.decode(s)
[deoplete]   File "/usr/lib/python3.6/json/decoder.py", line 342, in decode
[deoplete]     raise JSONDecodeError("Extra data", s, end)
[deoplete] json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 165)
[deoplete] Could not get completions from: typescript.  Use :messages for error details.
```

**Comment by mhartington** [comment]
Sorry for the silence on my end. Can you pull the latest and give it a test?

**Comment by Kasama** [comment]
Thanks, I just did pull the latest commit and it now works properly 👍
Keep up the good work!
