### ISSUE TITLE
Allow using Neomake

### ISSUE THREAD

**Issue by ahstro** [mhartington/nvim-typescript#52]
As mentioned in https://github.com/mhartington/nvim-typescript/pull/51#issuecomment-303113228

>When I build the neomake integration, I can add an option to open/close the loclist.
Still need to figure out how to do the neomake integration.

 - [ ] Create Neomake maker (see https://github.com/neomake/neomake/issues/1356#issuecomment-303201550)
 - [ ] "[A]dd an option to open/close the loclist"

**Comment by dlants** [comment]
I'm a bit confused about how this would interact with neomake, which currently gives two options for makers:

- get_list_entries (which I believe it expects to be synchronous... possible with a sync rplugin command, but would lock up the vim ui which is unfortunate)
- maker command (which runs a shell script, which doesn't really interact well with a remote plugin)

Do folks have an idea about how to make Neomake communicate with an rplugin?
