### ISSUE TITLE
question about how the plugin checks for the config file

### ISSUE THREAD

**Issue by tinchoz49** [mhartington/nvim-typescript#61]
Hi @mhartington how are you? I really like your work in this plugin, it's helping me a lot.

I have a question related with this function: https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim-typescript/__init__.py#L76

What do you think about only check if the (ts|js)config.json file exists in the root path of the project (like vscode does) instead of check each versioned files to find it?

Thanks!

**Comment by pyrho** [comment]
I think we can rely on looking only in the current working directory.
From [the typescript docs](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html):
> The presence of a tsconfig.json file in a directory indicates that the directory is the root of a TypeScript project.

I'm not sure what `Dir()` did (I feel dumb, but I can't seem to find the corresponding doc..), but if it was doing some I/O at instanciation, this will surely speedup startup time on large projects.

Let us know what you think @mhartington and if you agree I'll merge the `check-tsconfig-at-root` branch into master.

I tested it, and it looks fine:
![selection_139](https://user-images.githubusercontent.com/145502/28344825-62eadcd2-6c26-11e7-8d15-aee4a22d0f8c.png)

**Comment by mhartington** [comment]
So this is on purpose to fix https://github.com/mhartington/nvim-typescript/issues/46

Basically, if you start a typescript project, and then open the editor up in a subdirectory that does not have a tsconfig, tsserver will not start. My alternative was to check for the root of the project via version control, and go from that. A _better_ alternative would be to just recursively search the cwd and `cd ../` if one is not found.

**Comment by tinchoz49** [comment]
I think this a great idea:
> A better alternative would be to just recursively search the cwd and cd ../ if one is not found.

Maybe we can do a recursive lookup for the config file and stop in the home directory. With that approach we can define a global config and override the configuration if the project already has a config file.

Basically the same idea of how [ternjs](http://ternjs.net/doc/manual.html#project_file) detect the config files.

**Comment by pyrho** [comment]
@tinchoz49 see #62 .
