### ISSUE TITLE
Unable to locate tsconfig.json or tslint.json in path. Unable to debug required location of file.

### ISSUE THREAD

**Issue by Blue-Dog-Archolite** [mhartington/nvim-typescript#66]
# Problems summary

On running of `:CheckHealth` there is no reported `tsconfig.json` or `tslint.json` but both are present in the root of the project as well as the `src` directory. 

## Expected

I expect that `:CheckHealth` would locate the config files in either the source or the root of the project. I have reviewed the code and verified that the `.git` directory as well as the `.gitignore` files are present in the root of the project. It is my understanding that these are used to help locate the root of the project. 

I have attempted to debug the issue by writing to a file during execution of [TSFindConfig](https://github.com/mhartington/nvim-typescript/blob/3b71bb975dfef16a40f92aed6656f7d00ec3be68/autoload/health/nvim_typescript.vim#L42) during the CheckHealth call. and was supprised at the output. The results of [self._config.path](https://github.com/mhartington/nvim-typescript/blob/6d8ab96e53b25b8b1c554d6e35cd715cba4045c9/rplugin/python3/nvim-typescript/__init__.py#L73) is returning `None`

I have executed the CheckHealth from the root of the project, the src directory, as well as after opening a *.ts file.  as show here: 

![selection_049](https://user-images.githubusercontent.com/53378/28690503-ad8df3f8-72d6-11e7-9327-be1cd71aa8ca.png)

I have also added 

```
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_debug = 1
let g:deoplete#enable_profile = 1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

as was suggested in another post. This did not provide any useful information as Deoplete appears to be functioning as expected. 

## Environment Information

 * terminal: Gnome Terminal 3.24.2
 * vim/nvim version: NVIM v0.2.0 with Python2/3 support
 * Fedora 26
 * npm 5.3.0
 * Node 7.4.0
 * tsc --version - Version 2.4.2

## minimal vim rc 
```
filetype off                  " required

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/thief/.vim/dein/repos/github.com/Shougo/dein.vim
let s:dien_basepath = expand('~/.vim/dein/repos/github.com/Shougo/dein.vim')

" Required:
if dein#load_state('/home/thief/.vim/dein')
  call dein#begin('/home/thief/.vim/dein')

  " Let dein manage dein
  " Required:
  call dein#add('/home/thief/.vim/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('Shougo/deoplete.nvim')
  call dein#add('mhartington/nvim-typescript')
  call dein#add('HerringtonDarkholme/yats.vim')

  " Required
  call dein#end()
  call dein#save_state()

endif

" Required
filetype plugin indent on
syntax enable
```

## I am using the default angular project to reduce complexity

 1. `git clone https://github.com/angular/quickstart.git quickstart`
 2. `cd quickstart`
 3. `npm install`
 4. `tsc init` <- creation of default tsconfig.json and tslint.json
 5. `cp ts*.json src/`
 6. `nvim .`
 7. `:CheckHealth`

## Screen shot

![selection_048](https://user-images.githubusercontent.com/53378/28690283-d86745bc-72d5-11e7-88c4-65a0bf3b211c.png)

**Comment by mhartington** [comment]
Ahh, alright, I see whats up.

**Comment by Blue-Dog-Archolite** [comment]
Quality is rotten but this should show the example requested: 
```
nvim src/app/app.component.ts
:CheckHealth
```

![output](https://user-images.githubusercontent.com/53378/28691657-fa1c5418-72da-11e7-8a21-f52fe4329b7d.gif)


![selection_050](https://user-images.githubusercontent.com/53378/28691713-211c7b7e-72db-11e7-9316-791a3a0631c9.png)

**Comment by pyrho** [comment]
I reproduced the issue with your scenario @Blue-Dog-Archolite , but I think the issue would occur on any project, regardless of setup.

I did not affect functionality, only the health check, see the aforementioned PR.

Thanks for the thorough bug report !
