### ISSUE TITLE
Add a :TSTypeDef command

### ISSUE THREAD

**Issue by pyrho** [mhartington/nvim-typescript#70]
Similar to Tsuquyomi's `:TsuTypeDefinition`.

>:TsuTypeDefinition command is similar to :TsuDefinition. :TsuTypeDefinition navigates to the location where the type of the symbol under the cursor is defined.

This is pretty useful when types are inferred by the compiler.

**Comment by mhartington** [comment]
`:TSTypeDef` is added. Doc will follow in the AM.
