### ISSUE TITLE
Default mapping

### ISSUE THREAD

**Issue by yotamN** [mhartington/nvim-typescript#72]
I know that no mapping is a feature and I understand why not do this for commands that don't have a standard keybinding but for example KK or ctrl + ] are a standard in vim and it will be very convenient to have it as default. Ctags doesn't have typescript support anyway. Maybe add it as a variable option?

**Comment by mhartington** [comment]
So sorry, Im not really sure what `KK` and `ctrl-]` does 😄 

I've never really used ctags so Im not sure what the "expected" behavior would be. 
I'll add them if you think they'll be useful.

**Comment by yotamN** [comment]
[ctrl-\]](https://neovim.io/doc/user/tagsrch.html#CTRL-]) jump to the definition of the keyword under the cursor but it doesn't have TypeScript support so it just doesn't work.

[KK](https://neovim.io/doc/user/various.html#K) run a program to lookup the keyword under the cursor. The default is `man` but it make sense to open TSDoc for TypeScript. vim-go for example use it to open go doc.

**Comment by mhartington** [comment]
Sounds fair, I'll add a some optional keybindings that will mimic vim-go.

Here's `K` and `ctrl-]` working so far.

![key-map](https://user-images.githubusercontent.com/2835826/29525613-423d5a00-8661-11e7-94c3-00d29dc79e72.gif)

**Comment by huntie** [comment]
For reference: default mappings were added here and controllable via `g:nvim_typescript#default_mappings`.

https://github.com/mhartington/nvim-typescript/blob/a8ec49562ac7900758edabe07ba265523b8ed838/autoload/nvim_typescript.vim#L2-L6

I've found a mapping of `ctrl-]` to `:TSDef` to be a little more useful, since it will jump to any definition.

```
:nnoremap <silent> <c-]> :TSDef<CR>
```
