### ISSUE TITLE
[Feature Request] Show warnings on save

### ISSUE THREAD

**Issue by santiagodoldan** [mhartington/nvim-typescript#74]
# Problems summary
Are you planning to add a  list of syntax and semantics errors to Vim quickfix window? I've never built a plugin for vim, but if you need help, I'd like to add this feature.

**Comment by mhartington** [comment]
The pieces of this already exist right now, though Im looking to integrate with plugins like ALE or neomake. Just a bit pre-occupied with work at the moment to get things moving. Hoping to have more time in a few weeks to get this done.

**Comment by santiagodoldan** [comment]
Let me know if there's anything I can help you with, if you have a branch or something with your WIP I can take a look and see if I can finish it.

**Comment by prabirshrestha** [comment]
@mhartington FYI: In case you are looking into integrating with ALE. https://github.com/w0rp/ale/issues/517#issuecomment-323541716

**Comment by mhartington** [comment]
From my test, ALE should "just work" with it's tsserver maker, so nothing extra needed from me there.
Im working on getting things added to neomake first to get proper integration with nvim-typescript right now.

**Comment by prabirshrestha** [comment]
But doesn't that mean you now have two tsserver running or am I missing something? One for `nvim-typescript` and one for `ALE`? While this wouldn't be much problem for small projects, in large projects tsserver can be consuming several GB RAM.

I just added basic diagnostics support for [vim-lsp](https://github.com/prabirshrestha/vim-lsp) using `:LspDocumentDiagnostics` but need to update [typescript-language-server](https://github.com/prabirshrestha/typescript-language-server) to start publishing diagnostics messages. In this case there is only one instance of tsserver running.

**Comment by mhartington** [comment]
Added this last week. Closing!
