### ISSUE TITLE
Code completion via omnifunc

### ISSUE THREAD

**Issue by Perlence** [mhartington/nvim-typescript#76]
Is it possible to show code completion only when I press `<C-x><C-o>` and not every time I type?

**Comment by mhartington** [comment]
https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim-typescript/__init__.py#L543

Sure, you can set the omni-func to use `TSComplete`. You'd just need to disable Deoplete if you do

**Comment by Perlence** [comment]
Many thanks!
