### ISSUE TITLE
E117: Unknown function: TSOnBufEnter

### ISSUE THREAD

**Issue by blakef** [mhartington/nvim-typescript#80]
# Problems summary

Error on loading any `ts` file:

```
Error detected while processing BufEnter Auto commands for "*.ts":
E117: Unknown function: TSOnBufEnter
```
## Expected

No Error

## Environment Information

 * terminal: iTerm2 3.0.15
 * vim/nvim version:

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

* relevant plugins:
```
silent! let g:plugs['deoplete.nvim'].commit = '45f23f1'
silent! let g:plugs['yats.vim'].commit = '3bb50d3'
silent! let g:plugs['nvim-typescript'].commit = '8d09628'
```
## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mhartington/nvim-typescript'
call plug#end()
...
let g:deoplete#enable_at_startup = 1
...
```

## The reproduce ways from neovim starting

    nvim src/index.ts

## Example project repo?

This is almost certainly related to an environment incorrectly configured.  If it isn't then I'll put something together.

## Screen shot (if possible)

![screen shot 2017-10-10 at 09 49 16](https://user-images.githubusercontent.com/49578/31377539-3e6b9048-ada0-11e7-81d7-3df546418dbf.png)

![screen shot 2017-10-10 at 10 04 18](https://user-images.githubusercontent.com/49578/31378145-381e154c-ada2-11e7-9a10-e695379d994f.png)

**Comment by lucaspiller** [comment]
Did you run `:UpdateRemotePlugins` after installing this plugin? I came across it this morning, and I assumed that was needed just for Deoplete which i installed earlier, but it's needed for *this* plugin too.

**Comment by blakef** [comment]
That sorted it immediately.  I (wrongly) assumed that `UpdateRemotePlugins` was Dein specific.  The docs are clear to run it, but I'm not sure others won't make the same mistake.  Is it a bad idea to prefix the function: `:TSUpdateRemotePlugins`?

**Comment by pavilion** [comment]
I am having the same error.

1. node TS is installed.
2. node NeoVim is installed.
3. re-installed 'mhartington/nvim-typescript' 
4. executed :UpdateRemotePlugins after install
5. opened a ts file and still the same problem

**Comment by pyrho** [comment]
@blakef FYI `:UpdateRemotePlugins` is `neovim` specific, not part of any one plugin.
See: https://neovim.io/doc/user/remote_plugin.html#:UpdateRemotePlugins

**Comment by pyrho** [comment]
@pavilion Did you try what's mentioned in https://github.com/mhartington/nvim-typescript/issues/137 ?

> run the ./install.sh [located in the `nvim-typescript` install folder see if it helps with your issue 

This shouldn't be necessary but it worked for other users.
