### ISSUE TITLE
TSImport: incorrect import statements

### ISSUE THREAD

**Issue by matthjes** [mhartington/nvim-typescript#86]
# Problems summary
`TSImport` inserts import statements with wrong modules (here: it imports `@angular` instead of `@angular/core`)

## Expected
`TSImport` inserts import statements with correct modules.

## Environment Information

 * terminal: termite, zsh
 * vim/nvim version: nvim 0.2.0

## Provide a minimal vim rc with less than 50 lines (Required!)

```vim
" Used plugins                                                                   
call plug#begin('~/.config/nvim/plugged')                                                           
                                                                                                     
Plug 'bling/vim-airline'                                                                            
Plug 'tomasr/molokai'                                                                               
Plug 'morhetz/gruvbox'                                                                              
Plug 'Shougo/deoplete.nvim'                                                                         
Plug 'ctrlpvim/ctrlp.vim'                                                                           
                                                                                                     
" TypeScript                                                                                        
Plug 'leafgarland/typescript-vim'                                                                   
Plug 'mhartington/nvim-typescript'                                                                  
                                                                                                     
" Initialize plugin system                                                                          
call plug#end()   " Use deoplete                                                                                      

let g:deoplete#enable_at_startup = 1  
```
## The reproduce ways from neovim starting

1. Create Angular project.
2. Create module / component.
3. Open component .ts file.
4. Remove import for `Component`.
5. Move cursor to `@Component`.
6. Call `TSImport`.
7. Select module.

## Screen shot (if possible)

Example file, import for `Component` is missing.
![2017-10-18-212724_532x444_scrot](https://user-images.githubusercontent.com/1440866/31738809-1394e2ae-b44c-11e7-86fe-96478eddf392.png)
Select module.
![2017-10-18-212744_950x170_scrot](https://user-images.githubusercontent.com/1440866/31738811-13b7c5f8-b44c-11e7-848f-7bce8fa6f5f1.png)
Result (imported using module `@angular` instead of `@angular/core`).
![2017-10-18-212800_518x184_scrot](https://user-images.githubusercontent.com/1440866/31738812-13d96d20-b44c-11e7-898a-a5f55c5c713c.png)

**Comment by matthjes** [comment]
TSImport generates correct import statements if I want to import project components. It only fails when importing components from Angular modules.

**Comment by mhartington** [comment]
It might be because of the folder structure, IE the `@angular/core` Will need revisit the import parser

**Comment by symbyte** [comment]
@mhartington Seems likely, I'm seeing this same bug with any scoped npm packages i.e. `@myorg/mypackage` only importing `@myorg`.
