### ISSUE TITLE
Auto-complete seems to have broken in TypeScript 2.6

### ISSUE THREAD

**Issue by mixedCase** [mhartington/nvim-typescript#89]
Title.
Using nvim-completion-manager.
I can reliably get it to work again by downgrading to TypeScript 2.5 in my project's package.json

**Comment by epeli** [comment]
I just hit this too when I upgraded from `2.6.0-rc` to `2.6.1`. `TSType` and other commands are broken too so it's not just autocomplete.  No error messages. It just does not print anything.

tsserver seems to be running thou.

**Comment by mhartington** [comment]
It’s probably a change in the server response, similar things have happened before. I will investigate tomorrow

**Comment by mhartington** [comment]
just pushed a fix for this. Mind pulling down the latest and confirming? Works on my end

**Comment by mixedCase** [comment]
Seems to be working on my end as well. Thanks for the swift response!

**Comment by epeli** [comment]
Hmm, I seem to still hit this randomly. At editor startup it works fine for a while but then it just stops. `TSRestart` does not fix it. Only editor restart does.

Is there any way I could get some logging output?
