### ISSUE TITLE
Disable typechecking / setting error list

### ISSUE THREAD

**Issue by ianks** [mhartington/nvim-typescript#92]
I would like to use [ALE](https://github.com/w0rp/ale) do to my typechecking which levering nvim-typescript for renaming, importing, etc. Is there any way I can stop nvim-typscript from populating errors? 

Love the plugin, it has given me a huge productivity boost!

Cheers,
Ian

**Comment by mhartington** [comment]
Hi there! Glad to hear this plugin is useful for you. 

It actually does not do any type checking by default, so there should be anything extra needed. If you are seeing any errors populated it’s from ALE.
